anyproto/anytype-heart

- core/anytype/config/nodes/production.yml
> replace node conf

- core/block/simple/text/details.go
- core/block/simple/text/details_test.go
…ed, it becomes unselected in new object's name
> GO-1666 Fix creating an object from a template with a checkbox selected, it becomes unselected in new object's name

- core/block/import/importer.go
---
---
If import process finish with some error, we send `pb.ModelProcess_Error` state in event to client.
go-1800-finish-process-with-error-state-in-case-of-error-during
> GO-1800: finish process with Error state in case of error

- README.md
> GO-1727: Add usage info for grpcurl

- core/block/import/notion/api/page/page_test.go
- core/block/import/notion/api/property/databaseproperty.go
- core/block/import/notion/api/property/propertyitem.go
- core/block/import/notion/api/property/propertyobject.go
---
---
Add support for new unique_id property from Notion
> GO-1724: support new property type

- cmd/grpcserver/debug_not_win.go
- cmd/grpcserver/debug_win.go
- cmd/grpcserver/grpc.go
> GO-1825 Fix Sigusr1 for Windows

- deps/deps.go
- go.mod
- go.sum
> fix makefile

- space/localdiscovery/localdiscovery_android.go
> fix missing import

- core/filestorage/filesync/filesync.go
> GO-1848: Request SpaceStats asynchronously

- go.mod
- go.sum
- space/rpchandler.go
> GO-1865: Update any-sync to fix acl crash

- .github/workflows/test.yml
https://github.com/golang/go/issues/13560#issuecomment-288457920
---
---
> GO-1863 Exclude mocks from code coverage

- core/anytype/bootstrap.go
- pkg/lib/localstore/ftsearch/ftsearch.go
> GO-1707: Debug crash

- README.md
- go.mod
- go.sum
> GO-1880 Update go to 1.21

- core/anytype/bootstrap.go
> GO-1791 Add client/any-sync version to Graylog

- core/block/import/importer.go
---
---
TemDir service was provided in markdown import converter before it was initialized
> fix panic during markdown import

- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
> GO-332 Fix simple text editors paste tabs and order

- core/block/import/objectidgetter.go
---
---
If option has the same name as a relation, it breaks option creation
https://linear.app/anytype/issue/GO-1811#comment-0b560786
> GO-1811: fix not created relation options for Tag

- README.md
- docs/Codestyle.md
> GO-1940 Add code style rules

- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
> GO-1879 Fix the artist name clash

- docs/proto.md
- pb/protos/commands.proto
---
---
This PR removes unused Error codes from RPC responses
https://linear.app/anytype/issue/GO-1761/rpc-clean-up-unused-errors
> GO-1761 Remove unused RPC error codes

- core/block/editor/smartblock/smartblock.go
- core/block/editor/smartblock/smartblock_test.go
Updated version of details was discarded
> GO-1933: Fix appending pending details

- core/block/import/importer.go
- core/block/import/importer_test.go
- core/block/import/markdown/blockconverter.go
- core/block/import/mock.go
- core/block/import/objectcreator.go
- core/block/import/objectidgetter.go
- core/block/import/source/directory.go
- core/block/import/source/file.go
- core/block/import/source/zip.go
- core/block/import/types.go
---
---
Minor refactoring for import
> Cleanup import logs, simplify ObjectIDGetter interface, refactored some conditions

- core/block/editor/state/change.go
- core/block/editor/state/normalize.go
- core/block/editor/state/normalize_test.go
- core/block/editor/state/state.go
---
---
This PR fixes shortenned value assignment. Before changes it was not updated at all
https://linear.app/anytype/issue/GO-1501/limit-change-size
> GO-1501 Fix value assignment on value shortenning

- Makefile
- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
- util/strutil/str.go
> GO-332 Add proper copy-paste plain text rendering

- core/block/editor/converter/layout.go
> GO-1951 Fix collection of everything

- core/block/simple/dataview/view_changes.go
---
---
https://linear.app/anytype/issue/GO-1984/fix-event-on-setting-default-objecttype-to-view
> GO-1984 Fix default object type update

- core/account.go
- go.mod
- go.sum
> GO-1988: Fix marshal payload on deletion

- core/block/editor/workspaces.go
---
---
This PR fixes addition recommended objectTypes to relation when it is installed in account
https://linear.app/anytype/issue/GO-1987/relation-format-object-types-are-not-renamed
> GO-1987 Fix objecttypes setting to relations

- core/block/service.go
---
---
This PR fixes addition recommended objectTypes to relation when it is installed in account
https://linear.app/anytype/issue/GO-1987/relation-format-object-types-are-not-renamed
> GO-1987 Fix objecttypes setting to relations - feature/spaces

- core/block/import/notion/api/block/block.go
- core/block/import/notion/api/block/columns.go
- core/block/import/notion/api/block/div.go
- core/block/import/notion/api/block/file.go
- core/block/import/notion/api/block/link.go
- core/block/import/notion/api/block/link_test.go
- core/block/import/notion/api/block/mapper.go
- core/block/import/notion/api/block/retrieve.go
- core/block/import/notion/api/block/table.go
- core/block/import/notion/api/block/table_test.go
- core/block/import/notion/api/block/tableofcontent.go
- core/block/import/notion/api/block/text.go
- core/block/import/notion/api/block/text_test.go
- core/block/import/notion/api/block/textobject.go
- core/block/import/notion/api/client/client.go
- core/block/import/notion/api/context.go
- core/block/import/notion/api/database/database.go
- core/block/import/notion/api/database/database_test.go
- core/block/import/notion/api/page/page.go
- core/block/import/notion/api/page/page_test.go
- core/block/import/notion/api/page/task.go
- core/block/import/notion/api/property/databaseproperty.go
- core/block/import/notion/api/search/search_test.go
- core/block/import/notion/converter.go
> Fix concurrent map fatal error

- core/block/import/pb/converter.go
- core/block/import/source/directory.go
---
---
Imported files are closed before their were used
> Fix closing of imported files

- core/syncstatus/file_status_registry.go
Memory profile:
Before optimization:
270 Mb in Sys monitor
```
(pprof) top
Showing nodes accounting for 2046.94MB, 67.89% of 3015.21MB total
Dropped 768 nodes (cum <= 15.08MB)
Showing top 10 nodes out of 146
flat  flat%   sum%        cum   cum%
404.74MB 13.42% 13.42%   404.74MB 13.42%  github.com/dgraph-io/badger/v3.(*levelsController).pickCompactLevels.func1
277.54MB  9.20% 22.63%   277.54MB  9.20%  github.com/blevesearch/vellum.(*decoderV1).stateAt
235.51MB  7.81% 30.44%   235.51MB  7.81%  github.com/blevesearch/vellum.(*builderNodePool).Get
211.90MB  7.03% 37.47%   488.94MB 16.22%  github.com/blevesearch/vellum.(*FSTIterator).next
178MB  5.90% 43.37%      178MB  5.90%  github.com/blevesearch/vellum.(*unfinishedNodes).get
164.73MB  5.46% 48.83%   164.73MB  5.46%  bufio.NewWriterSize …
```
> Don't run unnecessary file's sync status indexing

- core/block/editor/clipboard/clipboard_test.go
- core/block/editor/clipboard/paste.go
> GO-1775 Fix removal of required blocks when pasting text

- .github/workflows/build.yml
- .github/workflows/test.yml
- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
- core/block/editor/clipboard/paste.go
- core/block/editor/state/change_test.go
- core/block/simple/text/text.go
- tests/testutil/state.go
> GO-132 Fix style preserving when copy n paste

- core/block/editor/state/normalize.go
> Fix block limit

- core/block/editor/state/change.go
- core/block/editor/state/normalize.go
- core/block/editor/state/state.go
- core/block/editor/state/state_test.go
- core/block/editor/stext/text.go
- core/block/editor/stext/text_test.go
> Fix - Remove blocks and text limits

- docs/Build.md
- docs/Protogen.md
>  Fix broken link add instructions in docs

- core/block/editor/state/normalize_test.go
> Fix - Comment normalizeSize tests

- core/block/editor.go
- core/block/editor/widget/widget.go
- core/object.go
- docs/proto.md
- pb/protos/commands.proto
- util/builtinobjects/builtinobjects.go
---
---
This PR fixes built-in usecases addition flow by sending events on widget blocks creation synchronously.
https://linear.app/anytype/issue/JS-2979/the-first-block-with-space-info-in-the-sidebar-is-absent
> GO-2041 | JS-2979 Sync widget update on account creation

- core/object.go
- pb/protos/commands.proto
---
---
Rename parameter in RPC protocol of ObjectImport
CollectionID -> collectionId
> GO-1896: Rename parameter in RPC protocol of ObjectImport

- core/block/service.go
---
---
This PR fixes template application. Type key is set from original state now
> Fix - Set type key from original state

- core/block/create.go
- core/block/editor/template.go
---
---
This PR sets sourceObject detail to new objects that were duplicated from existing ones or were created from a template
https://linear.app/anytype/issue/GO-2146/set-sourceobject-on-applytemplate-and-objectlistduplicate
> GO-2146 Set sourceObject if template applied or object duplicated

- .github/workflows/build.yml
- build.gradle
> GO-2159 Add maven and branch releases

- core/files/image.go
> GO-2122 Fix width filter issue with anytype logo

- core/block/editor/workspaces.go
> GO-2195: Add hook after apply for space view updates

- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
- .golangci.yml
- Makefile
- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
- core/block/editor/clipboard/paste.go
- core/block/simple/text/text.go
- tests/blockbuilder/constructors.go
> GO-132 Make style preserving more smooth

- go.mod
- go.sum
Reverts anyproto/anytype-heart#523
> Revert "Bump github.com/microcosm-cc/bluemonday from 1.0.25 to 1.0.26"

- core/block/editor/basic/basic.go
- core/block/editor/basic/basic_test.go
- core/block/editor/clipboard/paste.go
- core/block/editor/state/state.go
> GO-2051 Fix required blocks moving

- core/block/import/source/zip.go
- go.mod
- go.sum
> GO-2238 Fix non-unicode file names conversion

- core/block/import/converter/common.go
---
---
https://linear.app/anytype/issue/GO-2147/exportimport-issue-objects-with-uncategorized-status-relation-are-not
> GO-2147: fix objects with empty relation in kanban

- core/anytype/account/service.go
- core/application/account_delete.go
- go.mod
- go.sum
- space/delete.go
- space/spacecore/service.go
- space/spacecore/storage/storageservice.go
> GO-2199: Account delete

- core/block/editor/basic/details.go
- core/block/editor/table/table.go
- docs/Flow.md
---
---
https://linear.app/anytype/issue/GO-2216/when-i-select-the-object-type-the-selection-type-menu-should-disappear
> GO-2216 Remove type picker on type set

- space/loadingspace.go
> GO-2280: Check for loading mandatory documents error

- core/block/export/export.go
- core/block/import/pb/converter.go
- core/converter/pbc/pbc.go
- core/converter/pbjson/pbjson.go
- pkg/lib/localstore/objectstore/mock_objectstore/mock_ObjectStore.go
- pkg/lib/localstore/objectstore/objects.go
- pkg/lib/localstore/objectstore/objects_test.go
- util/testMock/objectstore_mock.go
---
---
* Add export of unique in snapshot. so we don't lose it during creation of object in import
* Extend `List` function of object store, so it can returns archived objects, because now it skip them by default
https://linear.app/anytype/issue/GO-2264/problems-of-importingexporting-space
> GO-2264 problems of importing/exporting space

- core/block/import/markdown/anymark/testdata/html_cases.json
- go.mod
- go.sum
> GO-2221 Fix list paste

- cmd/usecasegenerator/rules.go
- core/block/editor/basic/basic.go
- core/block/editor/converter/layout.go
- core/block/editor/smartblock/smartblock.go
- core/block/editor/state/normalize.go
- core/block/editor/state/state.go
- core/block/editor/template.go
- core/block/editor/template/template.go
- core/block/editor/template_test.go
- core/block/relation.go
- core/block/service.go
- core/subscription/cache.go
- core/subscription/diff_test.go
- pkg/lib/localstore/filestore/files.go
- util/slice/diff_test.go
- util/slice/slice.go
- util/slice/slice_test.go
---
---
This PR fixes object creation with default template for default type provided
https://linear.app/anytype/issue/GO-2253/plus-button-create-template-instead-of-object-with-default-type
> GO-2253 Remove template from type keys

- core/block/import/pb/converter.go
- core/block/import/pb/converter_test.go
---
---
Some users now use PB import to import their own snapshots (for example to test own imports)
Add snapshot validation to avoid errors during its creation. It also can be extensible 
https://linear.app/anytype/issue/GO-2249/panic-during-objectimport-in-latest-version
> GO-2249: add basic snapshot validation

- space/techspace/techspace.go
no need for mutex here. Fixes long AccountSelect
> GO-2297 fix techSpace wakeUpViews

- core/account.go
- core/filestorage/filesync/filesync.go
- core/filestorage/filesync/stats.go
- core/filestorage/rpchandler.go
- core/filestorage/rpcstore/inmemory.go
- core/filestorage/rpcstore/store_test.go
- docs/proto.md
- go.mod
- go.sum
- pb/protos/commands.proto
- pkg/lib/pb/model/models.pb.go
- space/create.go
- space/loadingspace.go
- space/space_personal.go
- space/techspace/techspace.go
- space/techspace/techspace_test.go
> GO-2290: Few space fixes

- core/configfetcher/configfetcher.go
---
---
This PR makes configfetcher send event only if AccountStatus has changed
https://linear.app/anytype/issue/GO-2098/do-not-send-accountupdate-event-if-nothing-is-changed
> GO-2098 Save last account status

- core/block/service.go
---
---
https://linear.app/anytype/issue/GO-2229/after-changing-the-source-in-the-set-the-template-is-not-updated
> GO-2229 Unset view template params on sourceSet

- core/block/import/converter/common.go
---
---
We don't store relation format in filter, when we create them. So I removed this redundant check
https://linear.app/anytype/issue/GO-2186/configurations-andor-layouts-lostmessed-after-exportimport
> GO-2186: configurations and/or layouts lost/messed after export/import

- core/block/import/creator/objectcreator.go
> Remove sensitive data log

- core/block/editor.go
- core/block/editor/clipboard/clipboard.go
- core/block/editor/file/file.go
- core/block/editor/state/state.go
- core/block/editor/state/state_test.go
> GO-2062 Fix root calc, fix file folder dropdown

- core/syncstatus/file_watcher.go
> Fix async write to map

- core/block/editor/template.go
> Fix panic on template migration

- core/block/editor/state/state.go
- core/block/object/objectcreator/creator.go
- core/block/template/service.go
- core/block/template/service_test.go
- util/pbtypes/pbtypes.go
- util/pbtypes/pbtypes_test.go
> GO-2235 Fix applytemplate cleared some existing details

- core/block/import/notion/api/block/link.go
- core/block/import/notion/api/block/link_test.go
> GO-2314: Links are imported with disabled icons for some reason

- core/block/import/pb/converter.go
- core/block/import/pb/converter_test.go
---
---
In case file doesn't have json or pb extension, we skip it and not return error
https://linear.app/anytype/issue/GO-2373/importing-a-space-with-objects-from-notion-ends-with-an-error
> GO-2373: importing a space with objects from Notion ends with an error

- core/block/object/objectcreator/set.go
- go.mod
> GO-2376 Fix set details propagating

- core/block/editor/smartblock/smartblock.go
- core/block/source/source.go
- core/block/source/sub_object_links_migration.go
- core/indexer/reindex.go
fix broken bundled sourceObject relation accidentally migrated to the space-derived id in https://github.com/anyproto/anytype-heart/pull/637
> GO-2400 broken sourceobject

- core/block/collection/service.go
take a lock after sb operation
> GO-2405 fix SubscribeForCollection deadlock

- core/block/template/service.go
- prefer featuredRelations/layout value from the template when applying to the state which already has one
> GO-2387 fix featured relations for template

- core/block.go
- core/block/cache.go
- core/block/collection/service.go
- core/block/create.go
- core/block/editor.go
- core/block/editor/basic/basic.go
- core/block/editor/basic/details.go
- core/block/editor/objecttype/objecttype.go
- core/block/object/objectcreator/creator.go
- core/block/template/service.go
- core/collections.go
- core/create.go
- core/navigation.go
- core/object.go
- core/relations.go
- core/template.go
- core/workspace.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
---
---
This PR adds lastUsedDate relation that will be set to details of type objects on every object creation or type switch
https://linear.app/anytype/issue/GO-2318/clients-need-new-relation-to-sort-object-types
> GO-2318 Add lastUsedDate relation

- core/block/template/service.go
- core/block/template/service_test.go
---
---
This PR fixes layout conversion on ObjectApplyTemplate
https://linear.app/anytype/issue/GO-2105/remove-description-from-featured-relations-for-all-types-except
> GO-2105 Set layout to blank template

- core/block/collection/service.go
> GO-2454 Do not delete collection with objects

- core/block/restriction/object.go
---
---
This PR adds TypeChange restriction to templates
https://linear.app/anytype/issue/GO-2360/add-typechange-restriction-to-the-templates-objects
> GO-2360 Add TypeChange restriction to templates

- core/block/bookmark/bookmark_service.go
make the rpc response consistent in case we already have bookmark for this URL
> GO-2528 CreateBookmarkObject: return details of object in case object exists

- space/spacecore/storage/spacestorage.go
- space/spacecore/storage/spacestorage_test.go
- space/spacecore/storage/storageservice.go
> GO-2524: Fix delete large space

- core/block/editor/page.go
- core/block/object/objectcreator/systemobjectreviser.go
---
---
This PR includes following fixes:
1. Links to object is no longer editable relation in object
2. All old objects get added Backlinks to their featured relations
https://linear.app/anytype/issue/GO-2512/backlinks-are-not-updated-in-all-usecases
> GO-2512 Add backlinks migration

- core/gallery/gallery.go
- core/gallery/gallery_test.go
> GO-2550 Add links to whitelist

- core/block/editor/basic/details.go
> Fix object deletion on ObjectToCollection

- util/testMock/objectstore_mock.go
---
---
Fixed not working test, by generating new mock
> Generate mock for ObjectStore

- core/block/import/common/collection.go
- core/block/import/csv/converter.go
- core/block/import/html/converter.go
- core/block/import/markdown/import.go
- core/block/import/notion/api/database/database.go
- core/block/import/pb/gallery.go
- core/block/import/pb/gallery_test.go
- core/block/import/pb/space.go
- core/block/import/txt/converter.go
---
---
https://linear.app/anytype/issue/GO-2300/clean-import-to-existing-space
> GO-2300: make widget collection not favorite for gallery

- core/block/editor/basic/details.go
- core/block/editor/objecttype/objecttype.go
- core/block/object/objectcreator/creator.go
- util/builtintemplate/builtintemplate.go
---
---
This PR updates LastUsedDate for object types only if object has origin==0 
Also we update LastUsedDate for object types created by user or added from marketplace
https://linear.app/anytype/issue/GO-2535/update-lastuseddate-relation-only-if-origin-==-0
> GO-2535 Update lastUsedDate for zero origin

- core/block/object/objectcreator/systemobjectreviser.go
---
---
This PR fixes update of system objects
https://linear.app/anytype/issue/GO-2536/links-from-object-is-not-added-for-objects-of-existing-accs
https://linear.app/anytype/issue/GO-2537/backlinks-and-outgoing-links-were-not-renamed-and-are-still-hidden-for
> GO-2536 | GO-2537 - Apply latest revision anyway

- core/block/editor/smartblock/links.go
- pkg/lib/core/smartblock/smartblock.go
---
---
https://linear.app/anytype/issue/GO-2559/homepage-has-an-untitled-object-widget-in-the-link-to-relation
> GO-2559 Exclude widget from backlinks

- core/block/object/objectgraph/graph.go
> GO-2589: Fix graph links

- space/create.go
- space/load.go
- space/loadingspace.go
- space/service.go
- space/space.go
- space/spacecore/storage/keys.go
- space/spacecore/storage/storageservice.go
> GO-2609: Remove just created and fix stack overflow in certain cases

- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
> GO-2573 Fix file creation from text

- space/load.go
- space/service.go
> GO-2612: Fix deadlock on app close

- space/clientspace/virtualspace.go
- space/internal/marketplacespace/marketplace.go
> Fix - Type prefix in marketplace

- .github/workflows/build.yml
fork in order to rollback the homebrew formula to have bigsur botttle
TODO: probably need to move bottles to our own servers
> ci: use our own fork for musl-cross on darwin

- core/block/editor/profile.go
- core/block/source/source.go
---
---
Add backlinks to featured relations of Profile
https://linear.app/anytype/issue/GO-2613/links-to-this-object-is-not-featured-in-the-profile-object
> GO-2613 Add backlinks to featured relations of Profile

- util/builtinobjects/builtinobjects.go
---
---
This PR fixes Home Page addition on experience installation
https://linear.app/anytype/issue/GO-2519/spacedashboardid-is-deleted-on-import
> GO-2519 Add home page from experience

- core/block/import/notion/api/block/file.go
- core/block/import/notion/api/block/file_test.go
- core/block/import/notion/api/block/link.go
- core/block/import/notion/api/block/link_test.go
- core/block/import/notion/api/block/text.go
- core/block/import/notion/api/block/text_test.go
---
---
Support following embed blocks from Notion:
1. Youtube
2. Vimeo
3. Miro
4. GoogleMaps
5. Mermaid
6. Soundcloud
https://linear.app/anytype/issue/GO-2620/add-support-for-embed-blocks-from-notion
> GO-2620: support embed blocks

- core/block/delete.go
---
---
This PR sets isUninstalled relation to true on template's deletion
https://linear.app/anytype/issue/GO-2409/default-template-reappears-after-deletion
> GO-2409 Uninstall template on deletion

- core/gallery/gallery.go
---
---
https://linear.app/anytype/issue/GO-2550/catch-404-error-on-downloadmanifest
> GO-2550 Catch 404 on DownloadManifest

- clientlibrary/service/lib.go
- clientlibrary/service/service.pb.go
- go.mod
- go.sum
- metrics/interceptors.go
- metrics/metrics.go
> GO-2050 Add long stacktrace to mobile clients

- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
> GO-2663 Fix code block copying

- space/internal/techspace/techspace.go
- space/internal/techspace/techspace_test.go
> GO-2739: Add spaceview check timeout

- core/block/import/common/objectcreator/objectcreator.go
---
---
This PR fixes lastUsedDate for types imported from bundled usecases
https://linear.app/anytype/issue/GO-2579/set-initial-state-in-lastuseddate-relation-for-note-page-task-set
> GO-2579 Set lastUsedDate for usecases

- core/block/editor/state/normalize.go
- core/block/editor/state/normalize_test.go
> GO-999: remove not needed code and add test

- util/reflection/util.go
> GO-2740 Fix crash in case of canceling the method call

- .github/workflows/build.yml
> GO-2762 Go 1.21 testdrive

- .github/workflows/build.yml
> GO-2762 Go 1.21 testdrive-2

- .github/workflows/build.yml
> GO-2762 Revert 1.20

- core/block/import/markdown/anymark/blocks_renderer.go
- core/block/import/markdown/anymark/blocks_test.go
- core/block/import/markdown/anymark/markdown.go
- core/block/import/markdown/anymark/renderer.go
- core/block/import/markdown/anymark/table_renderer.go
- core/block/import/markdown/anymark/testdata/html_cases.json
- core/block/import/markdown/anymark/testdata/md_cases.json
> GO-2148 Fix pasting the table

- core/block/editor/file/file.go
- core/block/service.go
- core/domain/objectorigin.go
---
---
`UploadFile` request is called with origin, which is used for `Origin` relation. But I forgot about it and didn't add `webclipper` origin.
So I add `Webclipper` origin for object and files
> fix webclipper panic

- .github/workflows/build.yml
> Fix inhouse

- core/block/object/objectgraph/graph.go
> GO-2808: remove sourceObject from graph

- .github/workflows/build.yml
- metrics/interceptors.go
> GO-2726 Track performance

- core/account.go
#883  has a wrong error code for app not running case
> GO-2849 add error code

- clientlibrary/clib/main.go
- clientlibrary/service/lib.go
- cmd/grpcserver/grpc.go
- pkg/lib/logging/logging.go
- util/vcs/vcs.go
for convenience of development on mobile platforms lets add SetLogLevel and RunDebugServer commands
> GO-2835 add mobile debug commands for pprof

- metrics/client.go
- metrics/service.go
> GO-2740 Fix crash in case closing the service

- .github/workflows/build.yml
> GO-2726 Fix ci

- core/block/editor/state/change.go
- core/block/editor/state/normalize.go
- core/block/editor/state/position.go
- core/block/editor/state/state.go
- metrics/amplitude/client.go
> GO-2726 Fix long state constructing

- core/history/history.go
[ ] - Remove AuthorName from protocol
> GO-2919: Fix version history: add correct participant id

- metrics/amplitude/client.go
> GO-2793 Do not send events to ampl and inhouse in debug builds

- space/clientspace/space.go
- space/internal/components/builder/builder.go
- space/internal/components/spaceloader/loadingspace.go
- space/internal/components/spaceloader/spaceloader.go
- space/internal/objectprovider/objectprovider.go
- space/internal/spaceprocess/loader/loader.go
- space/internal/spaceprocess/remover/remover.go
> GO-2923: Add disable remote load for removing spaces

- clientlibrary/service/service.pb.go
- core/anytype/config/config.go
- core/application/account_create.go
- core/application/account_select.go
- core/application/account_stop.go
- docs/proto.md
- pb/protos/commands.proto
- space/service_test.go
same as #920 but on top of 0.30.13 to make a hot-fix release
> GO-2927 RPC: add preferYamuxTransport field to accountSelect/create [backport 0.30.13]

- core/block/object/objectcreator/installer.go
- core/block/simple/file/file_test.go
https://linear.app/anytype/issue/GO-2805/i-cant-add-an-anytype-library-project
Install type or relation if it was moved to the bin
> GO-2805 Install archived subobjects

- space/internal/components/aclobjectmanager/aclobjectmanager.go
https://linear.app/anytype/issue/GO-2948/turn-off-multiplayer-notifications-in-release-3
> GO-2948: turn off multiplayer notifications in release 3

- core/block/import/common/filetime/linux.go
- go.mod
- go.sum
rewrite overflow check in ristretto
https://github.com/anyproto/ristretto/commit/2b23839cc50c5834c41386d9debf71d13f62d089
> ristretto: fix check on 32bit systems

- core/block/editor/profilemigration/profilemigration.go
- core/block/editor/profilemigration/profilemigration_test.go
- core/indexer/reindex.go
- space/clientspace/space.go
also fixes a bug with FulltextErase reindex flag not being saved
> GO-2986 Fix profilemigration type

- cmd/usecasevalidator/main.go
Fix files check in one more place
> GO-2673 Fix files treatment

- space/load.go
> GO-3003: Fix get status unlock

- cmd/grpcserver/grpc.go
> GO-2973 Add rss metric

- core/block/editor/state/change.go
- core/block/editor/state/state.go
- core/block/source/source.go
- core/debug/treearchive/treeimporter.go
- core/history/history.go
- docs/Debug.md
> GO-3010 Turn on fast building

- util/linkpreview/linkpreview.go
> GO-3032 Increase the fetcher limit up to 10mb

- Makefile
> GO-3082: Fix make install-dev-android

- core/space.go
> GO-3085: Fix space not deleting for participant when he/she was removed from space

- core/block/export/export.go
https://linear.app/anytype/issue/GO-2821/export-relations-from-setcollections
> GO-2821: fix export of object with inline set

- core/block/export/export.go
https://linear.app/anytype/issue/GO-3069/missing-images-when-exporting-objects-from-space
> GO-3069: Missing images when exporting objects from space

- cmd/usecasevalidator/main.go
- cmd/usecasevalidator/rules.json
- cmd/usecasevalidator/validators.go
https://linear.app/anytype/issue/GO-2673/implement-validator-on-usecase-addition-in-gallery
- Fix relation links in case they are missed
- Exclude validation of file keys
> GO-2673 Fix relation links in validator

- core/anytype/bootstrap.go
- go.mod
- go.sum
> GO-3072: Update any-sync to use nodeclient

- cmd/grpcserver/grpc.go
- cmd/grpcserver/performance.go
- cmd/perftester/main.go
> Add perf metrics

- core/block/editor/participant.go
https://linear.app/anytype/issue/GO-2950/make-anytype-identity-relation-as-featured-for-space-member-objects
Delegate identity injection to clients
> GO-2950 Remove identity from featured realtions

- core/anytype/bootstrap.go
> GO-3194 fix: register component

- core/nameservice/nameservice.go
- core/nameservice/nameservice_test.go
> GO-3221 fix: empty name

- core/indexer/reindex.go
- pkg/lib/localstore/ftsearch/ftsearch.go
> GO-3218 Wipe bleve properly

- core/anytype/config/nodes/production.yml
> GO-3245 Add NS, PP nodes to production config

- core/payments/payments_test.go
- core/payments/utils.go
> GO-3252 payments: prohibit from buying subdomains yet

- clientlibrary/service/lib.go
> GO-3315 fix QUIC on android [backport 0.32.x]

- core/files/image.go
- core/files/image_test.go
> GO-3242 Do not hide small files

- go.mod
- go.sum
> GO-2934 update any-sync

- core/block/editor/state/normalize.go
- core/block/editor/state/position.go
- core/block/editor/state/state.go
> GO-3423 Refactor and add logs

- core/filestorage/rpcstore/mock_rpcstore/mock_rpcstore.go
- pkg/lib/database/order.go
- pkg/lib/database/order_test.go
- util/testMock/anytype_mock.go
- util/testMock/file_service_mock.go
- util/testMock/history_mock.go
- util/testMock/mockKanban/kanban_mock.go
- util/testMock/mockSource/source_mock.go
- util/testMock/objectstore_mock.go
- util/testMock/sbt_provider_mock.go
> GO-2604 Do not include relation empty values in sorts

- core/block/export/export.go
- core/block/export/export_test.go
> GO-3215: add relation objects in export archive if there are relation

- pkg/lib/database/order.go
- pkg/lib/database/order_test.go
> GO-2604 Fix order

- core/block/editor/clipboard/clipboard.go
> GO-3393 Fix panics

- pkg/lib/database/order.go
- pkg/lib/database/order_test.go
> GO-2604 Fix sorting

- core/payments.go
- core/payments/payments.go
- docs/proto.md
- go.mod
- go.sum
- pb/protos/commands.proto
> GO-3466 RegisterPaymentRequest: add userEmail field

- pkg/lib/localstore/ftsearch/ftsearch.go
> GO-3401 Fix fts panic

- core/block/import/notion/api/page/page_test.go
- core/block/import/notion/api/page/task.go
- core/block/import/notion/api/property/propertyitem.go
https://linear.app/anytype/issue/GO-3475/anytype-helper-crashed-from-notion
> GO-3475: Anytype Helper Crashed from Notion

- core/block/editor/state/position.go
> GO-3392 Try to log potential panic

- core/payments/payments.go
- core/payments/payments_test.go
> GO-3501 get status should not overwrite cache if pp returned error

- core/payments/payments.go
- core/payments/payments_test.go
- docs/proto.md
- go.mod
- go.sum
- pb/protos/commands.proto
https://linear.app/anytype/issue/GO-3478/billing-id-for-ios
Remove billingID parameter from request, as it will be included in the very receipt
> GO-3478 Remove billingID from VerifyReceipt request

- space/internal/components/spacestatus/status.go
- space/internal/components/spacestatus/status_test.go
> GO-3495: Fix invalid change and add tests

- core/block/editor.go
- core/block/editor/clipboard/clipboard_test.go
- core/block/editor/clipboard/paste.go
- docs/proto.md
- pb/protos/commands.proto
> GO-2824 Implement base64 image upload capability

- core/files/files.go
- pkg/lib/mill/blob.go
- pkg/lib/mill/blob_test.go
- pkg/lib/mill/image_exif.go
- pkg/lib/mill/image_exif_test.go
- pkg/lib/mill/image_resize.go
- pkg/lib/mill/image_resize_test.go
- pkg/lib/mill/mill.go
Reverts anyproto/anytype-heart#1273
> Revert "GO-3512: Fix deduplication: fix EXIF mill"

- space/init.go
- space/service.go
- space/service_test.go
> GO-3559 tech space crash fix

- core/identity/ownidentity.go
- core/identity/ownidentity_test.go
> GO-3541 async fetch global name [backport v0.33.x]

- core/payments.go
- core/payments/cache/cache.go
- core/payments/cache/cache_test.go
- core/payments/payments.go
- core/payments/payments_test.go
> GO-3555: payments refactoring

- core/block/editor/smartblock/smartblock.go
https://linear.app/anytype/issue/GO-2140/events-for-closed-subscriptions-and-documents
Add context Id to objectClose events
> GO-2140 Add ctx to close event

- core/indexer/reindex.go
- core/indexer/reindex_test.go
https://linear.app/anytype/issue/GO-3602/do-not-reindex-marketplace-space-links
We should not reindex links and fileKeys of marketplace space, as we do not store them in badger
> GO-3602 Do not reindex links of marketplace

- core/block/import/common/syncer/file.go
- core/block/import/common/syncer/file_test.go
- core/block/import/common/syncer/mock_syncer/mock_BlockService.go
- core/block/import/common/syncer/types.go
- util/testMock/file_service_mock.go
https://linear.app/anytype/issue/GO-3586/import-failed-something-went-wrong-during-the-import
Don't fail import if file doesn't exist in the system, because it is not file upload error
> GO-3586: Import failed - something went wrong during the import

- core/block/editor/state/change.go
- core/block/editor/state/change_test.go
- core/history/history.go
- core/history/history_test.go
1. Don't add change if relation link for local relation added/removed
2. Move relation links to separate package to avoid import cycle
> GO-3699: sync details change lastModifiedDate/lastModifiedBy values and create a change

- core/block/editor/converter/layout.go
https://linear.app/anytype/issue/GO-3696/panic-on-createblanktemplatestate
Fix panic on converting blank template to set layout
> GO-3696 Fix panic on template creation

- pkg/lib/localstore/objectstore/queries.go
- pkg/lib/localstore/objectstore/queries_test.go
> GO-2973 Hotfix query for release

- metrics/events.go
- metrics/interceptors.go
- util/debug/debug.go
- util/debug/debug_test.go
> GO-3747 Improve stacktrace debug clickhouse

- metrics/interceptors.go
> GO-3747 Add AccountSelect Cold and Hot distinction

- .github/workflows/build.yml
> GO-3783 Fix perf tests

- core/block/editor/state/position.go
- core/block/editor/state/state.go
- core/block/editor/table/block.go
- core/block/editor/table/table.go
> GO-3781 Try fix cache

- core/payments/cache/cache.go
> GO-3790 payments cache: fix db close and races

- .github/workflows/build.yml
> GO-3823 Fix build

- core/filestorage/rpcstore/service.go
- core/peerstatus/status.go
- core/peerstatus/status_test.go
- space/spacecore/peermanager/manager.go
- space/spacecore/peermanager/manager_test.go
- space/spacecore/peerstore/peerstore.go
- make device count per space
- make it reactive via pool observer
> GO-3817 improve p2p status

- core/application/account_select.go
- metrics/interceptors.go
- metrics/service.go
> GO-3815 Fix accountStop sending

- core/syncstatus/spacesyncstatus/spacestatus.go
- core/syncstatus/spacesyncstatus/spacestatus_test.go
- core/syncstatus/syncsubscriptions/syncingobjects.go
- core/syncstatus/syncsubscriptions/syncsubscriptions.go
- core/syncstatus/syncsubscriptions/syncsubscriptions_test.go
> GO-3844: Fix and simplify subscriptions for sync status

- core/peerstatus/status_test.go
> GO-3857: fix events sending

- core/block/editor/table/block.go
- core/block/editor/table/block_test.go
- core/block/editor/table/editor.go
- core/block/editor/table/table.go
- core/block/editor/table/table_test.go
https://linear.app/anytype/issue/GO-3192/sometimes-clicking-an-object-doesnt-open-it-instead-it-leads-to-the
Include table mormalization fix to Release 6
> [release 6] GO-3192 - Fix table normalization

- core/block/object/objectcreator/installer_test.go
https://linear.app/anytype/issue/GO-3737/after-deleting-the-type-it-is-not-installed
Add unit test
> GO-3737 Add unit test for bundle objects reinstallation

- core/history/history.go
- core/history/history_test.go
https://linear.app/anytype/issue/GO-3870/historygetversions-ignore-limit-param
> GO-3870: fix history limit

- core/block/collection/service.go
- core/block/editor/dataview/dataview.go
https://linear.app/anytype/issue/GO-3849/need-to-save-the-setcollection-if-you-have-not-entered-a-name
Collection is not empty, if some object is added to it.
Set is not empty, if source is chosen.
> GO-3849 Do not GC set with source

- core/block/editor/smartblock/links.go
- core/block/editor/smartblock/smartblock.go
- core/block/object/objectlink/dependent_objects.go
- core/block/object/objectlink/dependent_objects_test.go
- core/converter/dot/dot.go
- core/converter/graphjson/graphjson.go
- core/history/history.go
https://linear.app/anytype/issue/GO-3923/images-are-not-added-to-links
PR includes refactoring of DependentObjectIds func. Now this function is used to fill **links** detail
> GO-3923 Include images in links

- .github/workflows/build.yml
> GO-3906 Fix tantivy build for ios

- core/payments/payments.go
- core/payments/payments_test.go
Change the logic a bit to suppress error and do not send it to client.
---
---
> GO-3702 GetAllTiers - supress error if no connectivity

- .github/workflows/build.yml
> Fix build-script

- pkg/lib/localstore/ftsearch/ftsearchtantivy.go
> GO-3970 Improve query quality

- go.mod
- go.sum
to include C lib update 1.0.3
https://github.com/chai2010/webp/pull/62
> upgrade webp

- core/block/editor/state/position.go
- core/block/editor/state/state.go
- core/block/editor/table/block.go
- core/block/editor/table/table.go
- core/block/source/source.go
> GO-3937 Get rid of cache

- core/block/editor/state/state.go
- core/block/import/common/common.go
- core/block/import/common/common_test.go
- core/block/import/common/objectcreator/objectcreator.go
- core/block/import/common/syncer/icon.go
- core/block/import/notion/api/commonobjects.go
- core/block/import/notion/api/commonobjects_test.go
- core/block/import/notion/api/database/database.go
- core/block/import/notion/api/database/database_test.go
- core/block/import/notion/api/page/page_test.go
- core/block/import/notion/api/page/task.go
- core/block/import/notion/api/property/relationsmaps.go
- core/files/fileuploader/uploader.go
Few improvements and fixes:
1. Fix upload of cover in page and database from Notion
2. Don't remove url from relation during updates of links in import
3. Remove unnecessary code from `ModifyLinkedFilesInDetails`, because cover relation is already checked in `FileRelationKeys()` function
4. Increase timeout for file loading from url during `UploadFile`
5. Don't duplicate Notion relations
> Notion import polishing

- core/block/editor/smartblock/links.go
- core/block/editor/smartblock/smartblock.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- pkg/lib/bundle/systemRelations.gen.go
- pkg/lib/bundle/systemRelations.json
https://linear.app/anytype/issue/GO-3965/provide-the-ability-to-distinguish-mentions-from-relations
Add mentions relation that aggregates all links from blocks
> GO-3965 Mentions relation

- README.md
---
---
This PR fixes the documentation: replace outdated link to usecasegenerator cli tool by usecasevalidator
> Fix link to cli tool documentation

- .githooks/commit-msg
- Makefile
> small fixes after clean build attempt; fix cp local deps

- docs/UsecaseValidator.md
> Fix Use Case archives validation tool docs

- core/block/editor/smartblock/links.go
- docs/ComplexFilters.md
https://linear.app/anytype/issue/GO-3965/provide-the-ability-to-distinguish-mentions-from-relations
- Add **mentions** relation to relation links
- Update doc on complex filters a lil bit :see_no_evil:
> GO-3965 Add mentions in relation links

- go.mod
- go.sum
> GO-4026: Remove old diff

- core/block/editor/template/collection.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
https://linear.app/anytype/issue/GO-4102/unhide-done-relation-and-template-obj-type
Make Template object type and Done relation non-hidden
> GO-4102 Unhide Done and Template

- go.mod
- go.sum
> GO-3980 Fix tantivy crash on linuxes

- .github/staging_fake.yml
- .github/workflows/perftests.yml
- .run/Run.run.xml
- Makefile
- cmd/perfstand/account_create/main.go
- cmd/perfstand/account_select/main.go
- cmd/perfstand/internal/util.go
> GO-3985 Try to add perf tests

- docs/Build.md
- flake.lock
- flake.nix
https://nixos.wiki/wiki/Flakes
> add nix flake with devShell

- clientlibrary/service/discovery_android.go
- net/addrs/common.go
- space/spacecore/localdiscovery/common.go
- space/spacecore/localdiscovery/localdiscovery.go
- space/spacecore/localdiscovery/localdiscovery_android.go
- space/spacecore/peer.go
> GO-4123 localdiscovery: fix ifaces refresh logic

- core/block/import/common/collection.go
- core/block/import/common/source/directory.go
- core/block/import/common/source/file.go
- core/block/import/common/source/source.go
- core/block/import/common/source/zip.go
- core/block/import/csv/converter.go
- core/block/import/html/converter.go
- core/block/import/html/converter_test.go
- core/block/import/markdown/blockconverter.go
- core/block/import/markdown/import.go
- core/block/import/markdown/import_test.go
- core/block/import/notion/api/database/database.go
- core/block/import/pb/gallery.go
- core/block/import/pb/space.go
- core/block/import/txt/converter.go
- util/builtinobjects/builtinobjects.go
https://linear.app/anytype/issue/GO-4038/create-collection-from-csv-file-in-markdown-import-of-notion-backups
> GO-4038: Create collection from CSV file in Markdown import of Notion backups

- core/object.go
> GO-4200 fix date mention

- core/object.go
- pkg/lib/database/database.go
- pkg/lib/localstore/objectstore/spaceindex/queries.go
> GO-3997 fix lists query

- core/block/detailservice/mock_detailservice/mock_Service.go
- space/internal/personalspace/personal.go
- space/internal/personalspace/personalloader.go
- space/load.go
- space/service.go
- space/service_test.go
- space/spacecore/mock_spacecore/mock_SpaceCoreService.go
- space/spacecore/service.go
- space/spacefactory/spacefactory.go
> GO-3631: Fixes

- core/navigation.go
https://linear.app/anytype/issue/GO-3941/a-click-on-a-strange-nameless-object-leads-to-another-space
Filter links in Navigation Flow by space id
> GO-3941 Filter flow links by spaceId

- clientlibrary/service/discovery_android.go
forgot to test the android build after the latest ctx changes
> GO-4247 android localdiscovery: add missing ctx

- space/service.go
Speed up app shutdown by closing spaces in parallel. Tech space closes only after all other spaces got closed
> GO-4243 app close many spaces

- core/block/editor/accountobject/accountobject.go
- core/block/editor/accountobject/accountobject_test.go
- core/block/editor/smartblock/mock_Indexer.go
- core/indexer/mock_indexer/mock_Indexer.go
- space/techspace/mock_techspace/mock_AccountObject.go
- space/techspace/techspace.go
> GO-4258: Private analytics id

- core/payments/payments.go
> GO-4271: fix get subscription status

- .github/workflows/build.yml
- .github/workflows/perftests.yml
- Makefile
- docs/Build.md
> GO-4156 Automate proper tantivy version downloading

- pkg/lib/localstore/ftsearch/ftsearchtantivy.go
- pkg/lib/localstore/ftsearch/ftsearchtantivy_test.go
> GO-4281 Close tantivy properly

- core/block/editor/archive.go
- core/files/fileobject/fileindex.go
- core/files/files.go
- core/filestorage/filesync/upload.go
- core/filestorage/rpcstore/client.go
- core/filestorage/rpcstore/clientmgr.go
- core/filestorage/rpcstore/store_test.go
- metrics/client.go
archive: can't set detail to object: build tree: tree storage already deleted
FileByHash: failed to retrieve from IPFS: CID not found
---
---
> GO-3957 Clean up logs

- go.mod
- go.sum
> GO-4304: Fix error handling spaces

- core/block/editor/spaceview.go
- core/block/editor/spaceview_test.go
> GO-4317: Date created fix

- pkg/lib/localstore/ftsearch/ftsearchtantivy.go
> GO-4297 Fix fts corruption

- core/anytype/account/profile.go
> GO-4333: Fix profile details

- core/block/object/treesyncer/treesyncer.go
- core/block/object/treesyncer/treesyncer_test.go
> GO-4371: Fix tree syncer space settings

- core/indexer/reindex_test.go
- core/syncstatus/detailsupdater/helper/helper.go
- core/syncstatus/detailsupdater/updater.go
> GO-4370: Fix chat sync status indexing

- core/payments/cache/cache_test.go
> GO-4332 fix payments/cache test flicker

- core/device.go
https://linear.app/anytype/issue/GO-4382/fix-devicenetworkstateset
> GO-4382: Fix DeviceNetworkStateSet

- core/block/delete.go
- core/block/detailservice/mock_detailservice/mock_Service.go
- core/block/detailservice/service.go
- core/block/detailservice/service_test.go
- core/block/detailservice/set_details.go
- core/block/import/common/objectcreator/objectcreator.go
- core/details.go
https://linear.app/anytype/issue/GO-4348/create-the-favorite-widget-if-it-is-not-already-in-the-sidebar-when-a
We should create Favorites widget on making some objects favorite
> GO-4348 Create favorite widget on favoriting

- go.mod
> GO-4170 Update go to 1.23.2

- go.mod
- go.sum
> GO-4409: Fix sync comparison

- core/block/object/treesyncer/treesyncer.go
> GO-4415: Fix tree syncer

- core/block/object/treesyncer/treesyncer.go
- core/block/object/treesyncer/treesyncer_test.go
- core/syncstatus/detailsupdater/updater.go
- core/syncstatus/detailsupdater/updater_test.go
- core/syncstatus/syncsubscriptions/syncingobjects.go
- go.mod
- go.sum
> GO-4417: hotfix release 7 1

- core/block/object/treesyncer/treesyncer_test.go
- core/syncstatus/detailsupdater/updater.go
remove problematic sync relation cleanup logic
> Release 7 fix

- .github/workflows/build.yml
Need to update go version in GitHub action scenario to run builds
> GO-3963 Update go in build GH action

- core/block/object/objectcache/mock_objectcache/mock_Cache.go
- core/wallet/mock_wallet/mock_Wallet.go
- go.mod
- go.sum
- space/clientspace/mock_clientspace/mock_Space.go
- space/internal/spacecontroller/mock_spacecontroller/mock_SpaceController.go
Update mockery to fix build and tests
> GO-3963 Update mockery

- core/block/object/treesyncer/treesyncer_test.go
- core/syncstatus/detailsupdater/updater.go
> Cherry pick fixes from release 7

- core/payments/payments_test.go
> GO-4431 payments: fix tests

- core/block/detailservice/relations.go
- core/block/detailservice/relations_test.go
https://linear.app/anytype/issue/GO-3964/provide-the-list-of-relations-on-the-layout-with-date-as-a-value
Value comparison should also be done to elements of list values
> GO-3964 Fix RelationListWithValue for mentions

- go.mod
- go.sum
> GO-4453: Update any-sync

- go.mod
- go.sum
> GO-4458: Fix rollback

- go.mod
- go.sum
> GO-4383 update any-store

- .github/workflows/build.yml
> GO-4500 Revive perf tests

- go.mod
- go.sum
- space/spacecore/peermanager/manager.go
> GO-4285 stream keep-alive

- core/block/widget.go
https://linear.app/anytype/issue/GO-4543/fix-blockwidgetsettargetid-panic
Fix panic on root block fetch
> GO-4543 Fix panic on SetWidgetBlockTargetId

- pkg/lib/database/filter.go
> GO-4557 fix race in filters

- core/block/import/importer.go
- core/block/import/importer_test.go
Add id for import notifications
https://linear.app/anytype/issue/GO-4476/a-new-message-does-not-appear-in-the-notification
> GO-4476: a new message does not appear in the Notification

- core/peerstatus/status_test.go
https://linear.app/anytype/issue/GO-4558/fix-race-in-p2p-status-test
> GO-4558: fix race in p2p status test

- .github/workflows/build.yml
> GO-4559 Fix min version

- core/block.go
> GO-4562 fix clipboard paste images

- .github/workflows/build.yml
- .run/Run.run.xml
- Makefile
- README.md
- go.mod
- go.sum
> Fix android crash

- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
https://linear.app/anytype/issue/GO-4277/make-the-list-of-relations-hidden-for-all-objects
Make DefaultValue, MaxCount, SetOf, GlobalName and AnytypeIdentity system relations hidden
> GO-4277 Make 5 relations hidden

- .github/workflows/golangci-lint.yml
- .github/workflows/test.yml
> .github/workflows/test.yml fix check licenses

- core/payments/payments.go
> GO-4578 payments: increase periodic interval

- core/block/object/objectgraph/graph.go
- core/block/object/objectgraph/graph_test.go
- go.mod
- pkg/lib/localstore/objectstore/fixture.go
- util/pbtypes/pbtypes.go
- util/pbtypes/pbtypes_test.go
https://linear.app/anytype/issue/GO-4577/mix-in-dates-to-objectgraph
Add date objects to graph
> GO-4577 Add date objects to graph

- core/anytype/bootstrap.go
- core/block/object/idderiver/deriver.go
- core/block/object/idderiver/idderiverimpl/impl.go
- core/block/source/service.go
https://linear.app/anytype/issue/GO-4552/make-clear-date-creation-logic
Add new implicit service to derive object ids for types and relations
> GO-4552 Type object id derivation service

- .github/workflows/build.yml
- .run/Run.run.xml
- Makefile
- go.mod
- go.sum
> GO-4591 Revert back to go 1.23

- core/files/files.go
https://linear.app/anytype/issue/GO-4274/fix-an-objectimportexperience-panic
Fix panic on ImageAdd
> GO-4274 Fix panic on image upload

- go.mod
- go.sum
> GO-4607: Update any-sync

- core/block/object/objectcache/tree.go
- core/block/object/objectlink/dependent_objects.go
- core/block/object/objectlink/dependent_objects_test.go
- core/history/history.go
- core/history/history_test.go
https://linear.app/anytype/issue/GO-4613/version-history-broken
Date objects were queried among all spaces including tech space
> GO-4613 Fix VersionHistory panic

- core/block/editor/page.go
Backlinks should be added to required internal relations of all pages, so we won't generate changes on relationLinks change
> Add backlinks to required internal relations

- core/space.go
- core/spaceview/order.go
- core/spaceview/order_test.go
- go.mod
- go.sum
Support case when we want to pin single view:
```
{
spaceViewId: "viewId",
spaceOrderView: ["viewId"]
}
```
> GO-4397: fix pin of single view

- space/coordinatorclient/coordinatorclient.go
we can't push multiple spaces simultaneously
> GO-4652 add limiter to coordinatorClient

- core/block/editor/template/template.go
https://linear.app/anytype/issue/GO-4263/make-tag-backlinks-as-featured-relation-for-all-files
Add tag and backlinks to featured relations of file objects
> GO-4263 Add tag and backlinks to featured

- Makefile
> GO-4639 Fix ios 15 rights

- .run/Run.run.xml
- core/anytype/bootstraptrace.go
> GO-3508 Add dependency tracer

- go.mod
- go.sum
> GO-4700 Update any-sync

- core/block_dataview.go
- core/broadcast_events.go
- core/chats.go
- core/core.go
- core/create.go
- core/debug.go
- core/details.go
- core/devices.go
- core/file.go
- core/nameservice.go
- core/navigation.go
- core/notification.go
- core/object.go
- core/payments.go
- core/relations.go
- core/space.go
- core/template.go
- core/workspace.go
> GO-4384 Fix panic recovery

- core/indexer/fulltext.go
- core/object.go
- pkg/lib/database/database.go
- pkg/lib/localstore/ftsearch/ftsearchtantivy.go
- pkg/lib/localstore/ftsearch/ftsearchtantivy_test.go
- pkg/lib/localstore/objectstore/spaceindex/queries.go
> GO-3997 Improve context menu search quality

- cmd/perfstand/internal/util.go
> GO-4693 Add os projection

- core/block/editor/template/template.go
https://linear.app/anytype/issue/GO-4263/make-tag-backlinks-as-featured-relation-for-all-files
Add Tag to details of file objects explicitly
> GO-4263 Add tag to details of file object

- .github/workflows/perftests.yml
- cmd/perfstand/account_create/main.go
- cmd/perfstand/internal/util.go
> added support for perftests on windows

- pkg/lib/localstore/objectstore/spaceindex/queries.go
> GO-4564 Fix mistake

- pkg/lib/localstore/ftsearch/ftsearchtantivy.go
> GO-4743 fix weights

- core/block/object/treesyncer/treesyncer.go
- core/block/object/treesyncer/treesyncer_test.go
- go.mod
- go.sum
> GO-4740: Derived tree fixes

- core/block/restriction/object.go
- core/block/restriction/object_test.go
https://linear.app/anytype/issue/GO-4724/remove-set-restriction-for-templates
Remove Template restriction from sets and collections to support set/collection templates
> GO-4724 Remove template restriction from sets

- core/block/object/objectcreator/object_type.go
- core/block/object/objectcreator/object_type_test.go
https://linear.app/anytype/issue/GO-4232/add-every-system-relations-to-recommended-relations-to-make-a-list-in
Exclude Description from recommended relations
> GO-4232 Exclude description from recommended relations

- core/application/profiler.go
> GO-4786 fix permissions

- core/block/editor/converter/layout.go
- core/block/editor/converter/layout_test.go
- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
- core/block/template/service.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- pkg/lib/bundle/systemRelations.gen.go
- pkg/lib/bundle/systemRelations.json
https://linear.app/anytype/issue/GO-4787/add-defaultview-and-defaulttype-relations
- add defaultViewType and defaultTypeId relations for set/collection types
- set these settings to first view of new objects with set/collection
> GO-4787 View relations for sets

- core/block/editor/converter/layout.go
- core/block/editor/converter/layout_test.go
- core/block/editor/template/collection.go
Add default collection relations to set during layout convertion
> GO-4347: When converting a Set to a Collection, Object Type / Tag / Description Relations is lost

- core/application/profiler.go
> GO-4786 fix permissions (#1969)

- core/application/profiler.go
> GO-4793 Fix full log dir export

- core/indexer/fulltext.go
> GO-4804 Fix memory overuse

- core/block/detailservice/mock_detailservice/mock_Service.go
- core/block/detailservice/service.go
- core/block/editor/basic/basic.go
- core/block/editor/basic/details.go
- core/block/editor/basic/details_test.go
- core/block/editor/participant.go
- core/block/editor/smartblock/smarttest/smarttest.go
- core/details.go
- core/object.go
- space/techspace/mock_techspace/mock_AccountObject.go
https://linear.app/anytype/issue/GO-4840/set-null-detail-on-objectrelationadd
We should send ObjectAmendDetails synchronously
> GO-4840 Send AmendDetails synchronously

- core/linkpreview.go
Spantaneous tidy of some RPC call
> Tidy LinkPreview call

- core/linkpreview.go
Use mustService instead of getService to call linkPreview method
> Fix linkPreview call

- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
https://linear.app/anytype/issue/GO-4929/new-setcollection-templates-have-basic-layout
On ObjectCreate for templates and types with set/collection layout we need to propagate layout from type object
> GO-4929 Fix layout for new set/collection templates

- core/block/template/service.go
https://linear.app/anytype/issue/GO-4763/user-cannot-change-the-set-template-during-the-set-creation
We should apply setOf detail from template
> GO-4673 Apply setOf from template

- .github/workflows/cla.yml
- .github/workflows/nightly.yml
- Makefile
> added nightly build ci

- core/publish/service_test.go
https://linear.app/anytype/issue/GO-4968/middleware-flaky-publishing-test-on-main
> GO-4968: fix flaky test

- Makefile
- core/block/restriction/object.go
https://linear.app/anytype/issue/GO-4971/add-restriction-delete-to-system-types
Add Delete restriction to system object types
> GO-4971 Add Delete restriction to sys types

- core/block/editor/converter/layout.go
- core/block/editor/converter/layout_test.go
https://linear.app/anytype/issue/GO-4993/default-grouprelationkey-view-setting-when-creating-new-object
If new set/collection has Kanban or Calendar view type chosen as default, groupRelationKey should be chosen among relation links listed in dataview block
> GO-4993 Insert groupRelationKey on set/collection creation

- core/publish/relationswhitelist.go
Include coverX and coverY relations to support reposition of cover in links
> GO-5057: image aspect ratio in Cover Link to

- util/text/text.go
- util/text/text_test.go
> GO-4037 Fix text truncate

- pkg/lib/gateway/gateway.go
> GO-4227 Make gateway port stable

- go.mod
- go.sum
> GO-2852 Fix exif stripper

- core/block/editor/smartblock/detailsinject.go
- core/block/editor/smartblock/detailsinject_test.go
ResolvedLayout should be updated on deletion of layout detail from state
> Fix resolvedLayout update on conflict resolution

- .github/workflows/golangci-lint.yml
- .golangci.yml
> fixed golangci-lint:

- makefiles/ci-pack-server.mk
> Fix build ci

- core/block/editor/converter/layout.go
- core/block/editor/converter/layout_test.go
https://linear.app/anytype/issue/GO-5182/allow-changing-type-to-bookmark
Allow changing layout from basic/todo/note/profile to bookmark and back
> GO-5182 Allow change type to Bookmark

- core/block/editor/page.go
- core/relationutils/recommended.go
- core/relationutils/recommended_test.go
https://linear.app/anytype/issue/GO-5165/add-to-all-existing-and-newly-created-types-feature-relations-object
Type, Tag and Backlinks realtions should be added to recommendedFeaturedRelations of all type objects
> GO-5165 Migrate types with recommendedFeaturedRelations

- core/filestorage/flatstore.go
- go.mod
- go.sum
- space/service_test.go
> GO-5191 Fix build

- cmd/grpcserver/performance.go
> GO-5209 Fix perf tests

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
https://linear.app/anytype/issue/GO-5221/rename-type-set-to-query
Rename Set to Query
> GO-5221 Rename Set to Query

- cmd/usecasevalidator/main.go
- cmd/usecasevalidator/validators.go
- cmd/usecasevalidator/validators_test.go
- Fix files and file objects processing
- Fix recommendedRelations validation
- Fix processing of invalid widget blocks
- Exclude relationLinks and fileKeys validation
- Support spaceDashboardId=lastOpened 
- Introduce unit tests
> Fix usecase validation

- cmd/grpcserver/performance.go
> GO-5246 Fix perf tests

- core/publish/relationswhitelist.go
https://linear.app/anytype/issue/GO-5293/support-custom-iconimage-for-types
> GO-5293: Support Custom IconImage for types

- core/files/fileobject/fileblocks/fileblocks.go
- core/files/fileobject/fileblocks/fileblocks_test.go
https://linear.app/anytype/issue/GO-5292/add-description-feature-to-every-file-object-as-a-1st-property-block
Add description relation block to file layout
> GO-5292 Add description to file blocks

- core/block/template/templateimpl/impl.go
- core/block/template/templateimpl/impl_test.go
https://linear.app/anytype/issue/GO-5294/add-templateid-options-on-object-creation
Add blank, default and lastEdited options for templateId on object creation
> GO-5294 Add templateId options

- pkg/lib/localstore/ftsearch/ftsearch.go
- pkg/lib/localstore/ftsearch/ftsearch_test.go
> GO-5305 Add plural name

- core/configfetcher/configfetcher.go
- core/debug/exporter/exporter.go
- core/event/event_grpc.go
- core/indexer/fulltext.go
- core/payments/payments.go
- core/subscription/dep.go
- space/internal/components/spaceloader/spaceloader.go
> GO-5309 Cleanup graylog

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
Plural name of Task was `Task`.
Updating it to proper plural: Tasks
---
---
> Update types.json to add correct Tasks plural name

- core/indexer/fulltext.go
- core/indexer/fulltext_test.go
- core/indexer/indexer.go
- core/indexer/indexer_test.go
- core/indexer/spaceindexer.go
- pkg/lib/localstore/ftsearch/autobatcher.go
- pkg/lib/localstore/ftsearch/ftsearch.go
- pkg/lib/localstore/ftsearch/ftsearch_test.go
- pkg/lib/localstore/objectstore/indexer_store.go
- pkg/lib/localstore/objectstore/indexer_store_test.go
- pkg/lib/localstore/objectstore/service.go
- pkg/lib/localstore/objectstore/spaceindex/fixture.go
- pkg/lib/localstore/objectstore/spaceindex/invalid.go
- pkg/lib/localstore/objectstore/spaceindex/objects_test.go
- pkg/lib/localstore/objectstore/spaceindex/queries.go
- pkg/lib/localstore/objectstore/spaceindex/store.go
- space/internal/components/aclobjectmanager/aclobjectmanager.go
- space/internal/components/aclobjectmanager/aclobjectmananger_test.go
- space/internal/components/spaceloader/spaceloader.go
- space/service.go
- space/service_test.go
- space/waiter.go
> GO-5322 Fix fts miss

- core/auth.go
> GO-5334: Add BlockLinkCreateWithObject to webclipper auth scope

- core/auth.go
- core/payments/payments.go
> JS-6614: move Explorer to the end

- space/internal/components/aclobjectmanager/aclobjectmanager.go
https://linear.app/anytype/issue/GO-5369/fix-panic-in-aclobjectmanager
> GO-5369: fix panic

- core/debug/netcheck.go
- go.mod
- go.sum
> GO-5377 update any-sync / fix closed conn release / quic write deadline

- pkg/lib/localstore/ftsearch/ftsearch.go
- pkg/lib/localstore/objectstore/service.go
> GO-5366 Add debug stat

- pkg/lib/core/tmp_dir.go
- pkg/lib/core/tmp_dir_test.go
> GO-4701 Add tmp cleanup

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
https://linear.app/anytype/issue/GO-5331/delete-priority-and-tasks-relations-from-the-task-type-library
Remove **tasks** and **priority** from recommended relations of **Task** type
> GO-5331 Remove tasks and priority from Task

- core/block/editor/widget.go
- allow to set details (for disableAutoWidgets)
- fix stateMigration version
> GO-5398 widget object fixes

- go.mod
- go.sum
> GO-5401: Update any-sync

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser_test.go
https://linear.app/anytype/issue/GO-5338/delete-all-system-descriptions-for-types-and-relations-for-users
- remove Description for new types
- remove Description from SystemObjectReviser, so it will not wipe out description from existing objects
> GO-5338 Remove description for types

- core/block/restriction/object.go
https://linear.app/anytype/issue/GO-5261/[next]-make-type-certain-deletable
> GO-5261 Make Note and Task deletable

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
https://linear.app/anytype/issue/GO-5443/provide-the-type-type-with-the-ishidden-relation-to-remove-it-from-the
> GO-5443 Make Type type hidden

- go.mod
- go.sum
> GO-5485: Update any-sync ignore migration errors

- go.mod
- go.sum
- space/spacecore/storage/migrator/migrator.go
- space/spacecore/storage/migrator/migrator_test.go
> GO-5570: Fix migration errors, update any-sync

- core/anytype/config/config.go
> OPS-703 edit publishAddr

- core/payments/emailcollector/emailcollector.go
> GO-5565 remove unneeded log msg

- .githooks/commit-msg
- core/auth.go
> JS-6656: Add ObjectCollectionAdd to API scope

- core/anytype/config/config.go
> OPS-703 publishAddr has been changed to anytype-publish-server.anytype.io

- core/wallet/mock_wallet/mock_Wallet.go
> GO-5629: Fix wallet tests

- go.mod
- go.sum
> GO-5667: Update protocol version

- core/pushnotification/service.go
> GO-5719 fix nil keys panic

- core/syncstatus/detailsupdater/updater.go
> GO-5768: Add chat derived to sync relations

- core/domain/value_test.go
- pkg/lib/database/filter.go
https://linear.app/anytype/issue/GO-5616/panic-on-objectimportexperience
- Use ToAnyEnc converter from domain pkg to build anyenc.Value from []string values
- Add Warn log on []string values in Eq filter to determine what client filters leaded to Eq+[]string filter
> GO-5616 Use ToAnyEnc converter

- core/block/editor/chatobject/chatobject_test.go
- core/block/source/sourceimpl/store.go
- core/indexer/reindex.go
- core/indexer/spaceindexer.go
- core/subscription/service.go
- pkg/lib/localstore/objectstore/indexer_store.go
- pkg/lib/localstore/objectstore/service.go
- pkg/lib/localstore/objectstore/spaceindex/delete.go
- pkg/lib/localstore/objectstore/spaceindex/relations.go
- pkg/lib/localstore/objectstore/spaceindex/update.go
- pkg/lib/localstore/objectstore/spaceresolverstore/store.go
- space/spacecore/storage/anystorage/clientstorage.go
> GO-5817 rollback in defer + subscription throttler fix

- core/block/object/treesyncer/treesyncer.go
> GO-5837: Fix data race in treesyncer

- core/notifications/notifications.go
- core/notifications/notifications_test.go
- space/internal/components/aclnotifications/notifications.go
- space/internal/components/aclnotifications/notifications_test.go
> GO-5855: Filter request to leave notifications 

- go.mod
- go.sum
> GO-5950: Fix quic connection close

- core/block/export/export.go
- core/block/export/export_test.go
- pkg/lib/localstore/objectstore/fixture.go
> GO-5989: Fix exporting missing objects in collection

- core/block/editor/smartblock/smarttest/smarttest.go
- core/block/import/common/objectcreator/objectcreator.go
- core/block/import/common/objectcreator/objectcreator_test.go
- pkg/lib/database/quickoptions_test.go
> GO-6012: Correct state in imported collections

- .github/workflows/smoke-tests.yml
- core/block/editor/widget.go
- core/block/editor/widget/widget.go
- core/block/editor/widget/widget_test.go
https://linear.app/anytype/issue/GO-6043/make-favorite-widget-under-chat-widget
Make favorite widget first one on first object being pinned
> GO-6043 Make Pinned widget first on pin

- .github/workflows/nightly.yml
> OPS-774 added diff-check and updated nightly version format

- .github/workflows/nightly.yml
> OPS-786 .github/workflows/nightly.yml added maven publish

- core/block/object/objecthandler/registry.go
- core/block/source/sourceimpl/source.go
https://linear.app/anytype/issue/GO-5805/fix-pages-widget-not-displaying-most-recent-page
Let's collect biggest lastModifiedDate and corresponding account key among all changes while building state
> GO-5805 Set biggest last modified date

- core/block/editor/order/order.go
- core/block/object/objectcreator/object_type.go
https://linear.app/anytype/issue/GO-6278/ensure-that-widget-for-the-newly-created-type-is-positioned-at-top-of
Ser orderId to all new custom types to set new types at list top
> GO-6278 Set orderId to all new custom types
