anyproto/anytype-heart

- core/block/import/csv/collectionstrategy.go
- core/block/import/csv/converter.go
- core/block/import/csv/converter_test.go
- core/block/import/csv/strategy.go
- core/block/import/csv/tablestrategy.go
---
---
We agreed to create separate collection for CSV import in case of "transpose rows and columns" option is turned on. It's needed to avoid messing transposed and original objects in 1 collection. Now tranposed file collection has different name <filename Transpose> and contains new created objects
https://linear.app/anytype/issue/GO-1786/re-importing-the-same-file-adds-objects-to-it
> GO-1786: create separate collection for CSV transposed option

- space/localdiscovery/localdiscovery.go
We had deadlock in the periodicCheck in case Close() called without the prior Run()
> GO-1845 localdiscovery: fix stop in case not enabled

- core/block/import/notion/converter.go
- core/block/import/notion/converter_test.go
---
---
Notion progress bar doesn't take into account creation of subobjects. So progress bar window can disappear earlier than import finishes.
https://linear.app/anytype/issue/GO-1884/the-bar-process-is-running-with-a-delay
> GO-1884: adjust progress bar

- core/block/editor/stext/text_test.go
- core/block/simple/text/text.go
> GO-1748 Do not inherit background color when splitting Code block

- core/block/import/importer.go
- core/block/import/objectcreator.go
---
---
There is a race between `ObjectImport` and `indexLinkedFiles`. That leads to situation, when flag `isImported` for files is set in badger after execution of `indexLinkedFiles`. It prevents files from loading to file nodes. So we set this flag before creating objects from snapshot in `ObjectCreator`. This guarantees, that flag is set before `indexLinkedFiles`. As a result file is loaded to node.
https://linear.app/anytype/issue/GO-1521/image-broken-after-migration
> GO-1521: fix not loaded images after migration

- core/block/import/importer.go
- core/block/import/notion/api/database/database.go
- core/block/import/notion/api/database/database_test.go
- core/block/import/notion/api/page/page_test.go
- core/block/import/notion/api/page/task.go
- core/block/import/notion/api/property/common.go
---
---
Now we replace property `Tags` with relation `Tag`. But we also want to replace `tags` property
> GO-1811: replace also "tags" property with relation Tag

- core/block/import/importer.go
- core/object.go
---
---
When computer wakes up after sleep mode, desktop do requests to restore tcp connections, but ObjectImport acquire mutex for whole application and block other requests. So we remove this mutex to allow other request execution. This solution helps to avoid stuck Logging screen, which is mentioned in the task.
It doesn't stop import, so it continue execution
https://linear.app/anytype/issue/GO-1774/there-is-an-exit-from-the-account-during-import-when-switching-to
> GO-1774: remove mutex from request

- core/block/import/markdown/anymark/testdata/html_cases.json
- core/block/import/markdown/anymark/underscore.go
---
---
When we replace "underline" CSS classes to "\<u\>" tag, there is a probability, that class name may contain special characters, so we escape them
https://linear.app/anytype/issue/GO-1770/research-root-cause-of-panic-during-objectimport
> GO-1770: fix panic in html import

- core/block/import/csv/converter.go
- core/block/import/html/converter.go
- core/block/import/markdown/blockconverter.go
- core/block/import/pb/converter.go
- core/block/import/pb/converter_test.go
- core/block/import/source/directory.go
- core/block/import/source/file.go
- core/block/import/source/source.go
- core/block/import/source/zip.go
- core/block/import/txt/converter.go
---
---
We allow to import files without extension in PB import to support `profile` file. It was used during migration process. But it also allowed to import other not supported files, which are without extension. 
So I remove importing of files without extension in PB import and extend `GetFileReaders` method with `includeFiles` slice. `includeFiles` contains files-exceptions, which are allowed to be imported. For Pb import it is `profile` and `config` files.
https://linear.app/anytype/issue/GO-1892/importing-protobuf-to-zip-ends-with-an-error
> GO-1892: not allowed to import files without extension in PB import

- core/syncstatus/update_receiver.go
---
---
This PR fixes status update for object types and relations. They are linked to Account object, so the bug was connected with incorrect order of instructions: firstly status of acc object was checked than statuses of subobjects were updated
https://linear.app/anytype/issue/GO-1911/sync-status-remains-preparing-for-types-relations-and-custom-objects
> GO-1911 Check account subobjects status first

- core/block/editor/widget.go
- util/builtinobjects/builtinobjects.go
---
---
This PR presents changes to Widget object creation flow.
As import does not support Widget right now (GO-2009 was created to fix that), all blocks in Widget are created manually according to specific usecase.
Skip and Strategic usecases share widget blocks order that differs from other usecases, so that situation was a push to that temporary solution
https://linear.app/anytype/issue/GO-1966/widgets-appearance-and-order
> GO-1966 Change widgets' order in Strategic usecase

- docs/proto.md
- pb/protos/commands.proto
- util/builtinobjects/builtinobjects.go
---
---
This PR presents new option for ObjectImportUseCase request - EMPTY. If this one is provided, no additional objects except predefined ones are created:
- profile
- account
- widget
- home (favorited objects holder)
https://linear.app/anytype/issue/GO-1948/add-empty-option-for-usecase-selection-to-add-opportunity-to-create
> GO-1948 Add Empty usecase option

- .github/workflows/build.yml
- .github/workflows/test.yml
1.20 was truncated to 1.2 [due to yaml parsing](https://github.com/actions/setup-go#v3)
> fix ci go version

- Makefile
---
---
I noticed misleading output when executing `make install-dev-js`. In the second-to-last line, it currently displays: "Run 'make install-dev-js' instead if you want to build&install into ../anytype-ts". This appears to be inaccurate because it's asking to run the exact command that was just executed.
I checked the Makefile for the echo statement. I traced it back to the install-dev-js target, which indirectly calls `build-js`, leading to `setup-go build-server protos-js`, and finally the echoing of the mentioned line. The line should not appear though, when running `make install-dev-js` directly.
To address this, I modified the install-dev-js target to directly call the three preceding targets: setup-go, build-server, and protos-js. This maintains the same functionality, while …
> Fix output of `make install-dev-js`

- core/block/collection/service.go
- core/block/collection/service_test.go
---
---
This PR fixes setting defaultObjectTypeId in collection views in case user cannot create objects via plus from them
https://linear.app/anytype/issue/GO-2012/convert-set-into-collection
> GO-2012 Exclude noncreatable types

- .githooks/pre-commit
- core/block/create.go
- core/block/editor.go
- core/block/editor/widget/widget.go
- core/block/service.go
- core/object.go
- docs/proto.md
- pb/protos/commands.proto
- util/builtinobjects/builtinobjects.go
---
---
This PR fixes built-in usecases addition flow by sending events on widget blocks creation synchronously.
https://linear.app/anytype/issue/JS-2979/the-first-block-with-space-info-in-the-sidebar-is-absent
> GO-2041 | JS-2979 Sync widget update on account creation - spaces

- core/files/debug.go
- core/files/files.go
- core/filestorage/filesync/upload.go
- pkg/lib/localstore/filestore/debug.go
We want to release hotfix for the 0.28.5 release
This PR cherry-picks #435 on top of version/0.28.5 branch
> Go-2064 memory leak starts at about 12gb and grows to 24gb hotfix

- core/block/collection/service.go
- core/block/collection/service_test.go
---
---
This PR allows Collections and Sets be defaultObjectTypeID value for collection views converted from set
https://linear.app/anytype/issue/GO-2012/convert-set-into-collection
> GO-2012 Allow set and collection as defaultType on collection convert

- core/block/bookmark/bookmark_service.go
- core/block/editor.go
- core/block/editor/bookmark/bookmark.go
- core/block/simple/bookmark/bookmark.go
- util/linkpreview/linkpreview.go
- change userAgent used for preview from `Googlebot/2.1` to `AnytypeBot`. Looks like GoogleBot ug got abused and strictly checked with IP ranges of google services by popular services like cloudflare
- check http status code. If code != 200 then do not fill the web preview
- do not set error code for the block. It still creates the underlying bookmark object but block looks ugly
Later we will add the background bookmark refetcher for the offline/ratelimited cases
> GO-2213 bookmark change user agent

- core/block/import/markdown/import.go
---
---
The problem is that we add to result error from url.PathUnescape. But this error considered as warning, and we already log it.
https://linear.app/anytype/issue/GO-2118/objectimport-code-3-msg-import-type-markdown-error-invalid-url-escape
> GO-2118: ObjectImport: code: 3 msg: import type: Markdown: error: invalid URL escape "%!H(MISSING)

- core/block/editor/template.go
- core/block/object/objectcreator/creator.go
---
---
This PR cancels error return in case template provided in object creation commands is deleted
https://linear.app/anytype/issue/GO-2284/use-blank-template-in-case-provided-template-is-deleted
> GO-2284 No error on deleted template

- core/block/import/markdown/anymark/renderer.go
---
---
`ForceCloseTextBlock` for some reasons deletes text block from `openedTextBlocks`, so it can't be created. That's why I change it to simple `CloseTextBlock`, where text block is not deleted
https://linear.app/anytype/issue/GO-2271/when-importing-md-the-first-block-is-deleted
> GO-2271: when importing MD, the first block is deleted

- pkg/lib/datastore/clientds/clientds.go
- pkg/lib/localstore/objectstore/queries.go
I did all the benchmark in this way:
- Run desktop anytype app with 3700 objects in the objectstore (so it do the objectSearch under the hood and warm-up the cache)
- Run 1000 iterations of ObjectSearch with a filter that matches nothing
1. Main branch
disk = SSD
blockCache = 256mb
valuethreshold = 1024*1024
iterator.valuePrefetch=true
compression = snappy
**Result:
4518ms for 1000 iterations**
2. Main branch + disabled valuePrefetch for iterator
disk = SSD
blockCache = 256mb
valuethreshold = 1024*1024
iterator.valuePrefetch=false
compression = snappy
**Result:
1948ms for 1000 iterations**
3. all badger options tunes(this branch)
disk = SSD
blockCache = 0mb
valuethreshold = 1024*1024
iterator.valuePrefetch=false
compression = none
**Result:
1761ms for 1000 iterations**
4. This branch on …
> Go-2131 optimize badger memory consumption

- core/block/restriction/object.go
- space/objectprovider/objectprovider.go
- space/space.go
- fallback to objectRestrictionsBySBType to have the single source of truth
- add restrictions to static Identity object
- add workaround to tolerate the existing error if Profile object has been removed
> GO-2313 add restrictions to profile, identity

- core/object.go
- docs/proto.md
- pb/protos/commands.proto
---
---
This PR fixes update of object type in case it was updated vai widget
https://linear.app/anytype/issue/GO-2035/new-type-is-not-displayed-immediately-when-changing-via-widgets
> GO-2035 Send sync event on ObjectListSetObjectType

- core/block/template/service.go
- core/block/template/service_test.go
---
---
https://linear.app/anytype/issue/GO-2335/use-blank-template-in-case-template-is-archived
> GO-2335 Create blank template in case it is archived

- core/block/collection/service.go
- core/block/collection/service_test.go
---
---
This PR fixes setting defaultObjectTypeId to views during conversion from set to collection.
Now all object types has its own local-space id, so the mechanism was broken
https://linear.app/anytype/issue/GO-2012/convert-set-into-collection
> GO-2012 Fix set to collection convertion

- core/block/editor/smartblock/smartblock.go
- core/block/editor/state/change.go
- core/block/editor/state/change_test.go
- core/block/source/source.go
- core/block/source/sub_object_links_migration.go
- core/domain/uniquekey.go
- core/indexer/reindex.go
- handle wrong bundled objectTypes
- migrate state on Init so it will handle object creation
- migrate state on ResetToVersion so it will handle history version revert operation
> GO-2390 fix subobject migration

- core/subscription/service.go
- core/subscription/service_test.go
---
---
https://linear.app/anytype/issue/GO-2116/add-test-for-function-subscribeidsreq-in-subscription-package
> GO-2116: add tests for subscriptions

- core/block/import/importer.go
- metrics/events.go
---
---
Add events for amplitude to track metrics when user start import, but not finish it (close application or turned off device and etc)
https://linear.app/anytype/issue/GO-2343/import-notion-timeout-check-graylog-how-many-notion-imported-started
> GO-2343: add import start and import finish events to amplitude

- core/block/import/pb/gallery.go
- core/block/import/pb/gallery_test.go
---
---
Currently widgets are not updated, when user delete object, which was linked to widget objects. So that leads to a situation, when widget object contains not existing objects in links blocks. During import such objects don't exist in archive. So we skip such objects during gallery import and not add them to widget collection
> GO-2556: experience creates an empty widget collection

- space/space.go
because we calculate all derived ids on the space init there is no need to wait for load
> fix reindex deadlock

- pkg/lib/localstore/objectstore/badger_helpers.go
iterator key can't be sed outside of iterator without copy
> fix iterateKeysByPrefixBatchedTx

- space/internal/components/spaceloader/spaceloader.go
- space/internal/techspace/techspace.go
- space/internal/techspace/techspace_test.go
> GO-2636: Add responsible peers to space loader

- go.mod
- go.sum
- pkg/lib/datastore/clientds/clientds.go
- pkg/lib/datastore/clientds/syncer.go
- switch badger to include corrupted db check (with indexLen = 0 ) https://github.com/anyproto/badger/tree/fix-corrupted-db-checksum-check
- switch to ristretto fork to have msync impl on windows  https://github.com/anyproto/ristretto/tree/msync-win
- add regular mmap sync with configurable interval of inactivity (every 1 min)
- add fallback every 500 db versions (in case of active db writes)
- remove and rebuild localstore db(not spacestore) in case of checksum errors
> GO-2658 add syncer, switch ristretto

- core/block.go
- core/block/import/common/objectcreator/objectcreator.go
- core/block/import/markdown/anymark/anyblocks.go
---
---
Add root block to response to preserve structure of blocks
https://linear.app/anytype/issue/GO-2585/implement-command-which-shows-preview-of-generated-blocks
> GO-2585: add root block in response

- .github/workflows/build.yml
- Makefile
- clientlibrary/service/fixtz_android.go
- clientlibrary/service/fixtz_ios.go
- clientlibrary/service/fixtz_skip.go
- clientlibrary/service/lib.go
- cmd/grpcserver/grpc.go
- util/vcs/vcs.go
https://github.com/golang/go/issues/20455
https://github.com/golang/go/issues/20797
Tested on both iOS and Android. Fixes problems with relative filters, e.g. Today
Android seems to have tzdata on some devices and I was not able to fine a way to read it on iOS. I have embed [tzdata](https://cs.opensource.google/go/go/+/refs/tags/go1.21.5:src/time/tzdata/tzdata.go) on both of them and it should add 450kb to the binary/heap size
> Go 2643 fix tz on android and ios

- core/block/template/service.go
- core/block/template/service_test.go
---
---
This PR makes sourceObject and layout values of template state more prioritized than in origin state
https://linear.app/anytype/issue/GO-2455/template-dont-change-layout
https://linear.app/anytype/issue/GO-2570/relation-source-object-does-not-update-the-linked-template-when
https://linear.app/anytype/issue/GO-2575/template-selector-not-working-correctly
> GO-2455 | GO-2570 | GO-2575 - Save template details

- space/internal/shareablespace/shareable.go
> GO-2725: Return initial mode instead of panic

- core/block/editor/state/normalize.go
> GO-2726 Fix memory allocation when pasting huge amount of blocks

- core/block.go
- util/linkpreview/linkpreview.go
---
---
From `og.Fetch` we get decoded to non-utf response in case of non-utf charset on web-site. So we need to decode it to UTF
So I use function `DetermineEncoding` from `net` and use it to decode response
Fix BlockPaste response, as it always return code=2, even when we don't have error.
> [Webclipper] Add detection of encoding and decode to utf

- Makefile
This PR adds commands to simplify android/ios development while changing the anytype-heart head locally
Android
`make install-dev-android` 
- build android lib
- copy lib to `../anytype-kotlin` alongside with proto files
- replace versions in config with the library's sha hash
- run the gradle publish and proto files normalisation
iOS
`make install-dev-ios`
- build iOS framework
- copy framework to `../anytype-swift` alongside with proto files and system relation jsons
> GO-2798 commands for mobile devs

- core/block/simple/dataview/dataview.go
- core/block/simple/dataview/dataview_test.go
- core/block/simple/dataview/views.go
- core/subscription/collection.go
- core/subscription/service.go
https://linear.app/anytype/issue/GO-2668/collections-filters-are-not-working
Objects set in filters of Collection views were not shown up, because desktop client did not recieve their details on ObjectSearchSubscribe.
This PR contains two fixes: 
1. For desktop, that takes details from dependencies in ObjecSearchSubscribe response. Collection subscription was not taking filterObjectIds into account, while initialising dependency subscription.
2. For mobile clients, that take details from smartblock view on ObjectOpen. We did not analyze filters on collecting dependent ids from dataview block.
> GO-2668 Add details of objects in dataview filters

- core/account.go
- core/application/sessions.go
handle the case when app(account) was not started and return the error
> GO-2849 link challenge app not running case handle

- core/converter/html/html.go
https://linear.app/anytype/issue/GO-2848/check-lastopenedtags-length-on-blockcut
Check of first value in lastOpenedTags is redundant, as we do this check in closeTagsUntil, so we should check array emptiness only on lastOpenedTags shortening to avoid panic
> GO-2848 Fix panic on html render

- pkg/lib/mill/image_resize.go
https://linear.app/anytype/issue/GO-2866/icons-of-bookmarks-are-missed
Problem:
We can't load icons in bookmarks with format .ico. That's because we assume that mime type of .ico image is `ico`, but actually it is `vnd.microsoft.icon`
https://github.com/anyproto/anytype-heart/blob/ad227be334f762df0b3581a0ad8345110862887d/pkg/lib/mill/image_resize.go#L43
Solution
Change format `vnd.microsoft.icon`, so now we can load such files as images and show in bookmark
> GO-2886: change ico to vnd.microsoft.icon format

- util/builtinobjects/builtinobjects.go
https://linear.app/anytype/issue/GO-2781/no-notification-on-internet-loss-on-objectimportexperience
On internet loss during import of experience from gallery we:
1. Cancel progress bar
2. Send notification
> GO-2781 Notification on internet loss on ImportExperience

- core/block/import/pb/converter.go
https://linear.app/anytype/issue/GO-2908/the-import-of-the-space-passed-with-an-error
If we have Json or Pb `files` in files directory from export, we try to import them too. So I decided to skip `files` directory during import. 
I decided that, because we have task to implement export structure https://linear.app/anytype/issue/GO-2746/export-structure. So we will import from relations/relationsOptions/objects/types directories and skip `files` any way. So it is not a hack.
> GO-2908: fix import from files directory

- core/block/editor/state/position.go
- core/block/simple/text/text.go
https://linear.app/anytype/issue/GO-115/blockpositionreplace-works-incorrectly
Give the interface more understandable name
> GO-115 Rename interface

- core/block/editor/profile.go
- core/block/editor/profilemigration/profilemigration.go
- core/block/editor/profilemigration/profilemigration_test.go
- core/block/simple/bookmark/bookmark.go
- core/block/simple/dataview/dataview.go
- core/block/simple/embed/embed.go
- core/block/simple/file/file.go
- core/block/simple/link/link.go
- core/domain/uniquekey.go
- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- space/clientspace/space.go
we deprecate the ability to store any custom state inside the personal space's derived Profile object. From now on it only supposed to store name/image.
Because some user may have some data within it this migration extract this into the new object. But only in case there are any non-empty blocks within it.
> GO-2945 add old profile migration

- core/block/object/objectcreator/systemobjectreviser.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- space/clientspace/space.go
- update assignee/author/lastModifiedBy relation target types to include participant
- change the logic of reviseSystemObject. Do not update same revision object
- add an optimisation to migrationProfileObject
> Bundled Type/relations fixes

- core/block/service.go
- docs/proto.md
- pb/protos/commands.proto
https://linear.app/anytype/issue/GO-2968/
In weblclipper we don't add parsed blocks from web page to Anytype object if the `addPageContent` flag is not set in `ObjectCreateFromUrl` request
> GO-2968: add addPageContent flag

- core/block/template/service.go
https://linear.app/anytype/issue/GO-2883/lastuseddate-is-not-updated-when-creating-an-object-using-a-template
We should ignore Origin value of template object when creating new object
> GO-2883 Ignore origin in custom templates

- cmd/usecasevalidator/main.go
- cmd/usecasevalidator/validators.go
1. Some files are coming with `files\...` name, not `files/...` in experience archive, so we need to check these names as well
2. Fix error check in case of relation link absence in snapshot
> GO-2893 Fix files treatment in validator

- core/auth.go
return proper grpc code [UNAUTHENTICATED](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)
> GO-1936 grpc auth: return proper grpc code

- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_test.go
- core/block/import/markdown/anymark/blocks_renderer.go
- core/block/import/markdown/anymark/renderer.go
In case user paste the text with a hugge amount of text without double line breaks(\n\n) it will results in huge text blocks created. It is very bad from multiple sides.
- every change to text block contains the full text of block
- large text block is hard to render on client (per-block virtualisation is not possible)
- full-text is also indexing per-block, making it consume a lot of memory during the indexing
This PR introduces the soft limit the breaks block on a single line ending in case it exceeded the soft limit.
Currently I set the limit to 1024 symbols. 
Also, in case markdown parsing was failing(e.g. in case text has invalid markdown sequences), text was splitting by a single line break. I've changed the logic to be consistent with anymark behaviour
> GO-2664 anymark: introduce TextBlockLengthSoftLimit

- core/identity/identity.go
- core/payments/payments.go
- core/payments/payments_test.go
https://linear.app/anytype/issue/GO-2734/add-cache-for-client-to-resolve-id-name
We should fetch globalName for local profile directly from Naming Service, so `identity` service updates details of local participant in all spaces
> GO-2734 Resolve names directly from NS

- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
https://linear.app/anytype/issue/GO-2964/remove-maxcount=1-from-restrictions-relation
We should remove maxCount=1 from Restrictions relation, as it is []int
> GO-2964 Unset maxCount for restrictions

- core/block/import/common/common.go
- util/os/error.go
- util/os/error_test.go
https://linear.app/anytype/issue/GO-2811/importing-from-notion-ends-with-an-error
1. Anonymize returned error in ObjectImport response by masking url
2. Fix import of notion icons. We didn't take into account that originally iconImage field in text block contained url to Notion icon. So Notion icons weren't imported, because they were considered as missing objects
> GO-2811: Importing from Notion ends with an error

- core/block/editor/participant.go
https://linear.app/anytype/issue/GO-2950/make-anytype-identity-relation-as-featured-for-space-member-objects
Change featured relations order:
type -> AnyID -> backlinks
> GO-2950 Change relations order

- core/identity/identity.go
- core/payments/payments.go
- core/payments/payments_test.go
https://linear.app/anytype/issue/GO-2734/add-cache-for-client-to-resolve-id-name
Save globalName of myIdentity directly, as NS need some time to process newly registered name
> GO-2734 Add globalName directly

- space/internal/shareablespace/shareable.go
- space/service.go
- space/service_test.go
Fix a bug when we could change status to removing for the spaces that were previously deleted by the space member
> GO-3177: Fix removing spaces

- core/payments/payments.go
- core/payments/payments_test.go
- docs/proto.md
- pb/protos/commands.proto
https://linear.app/anytype/issue/GO-3023/implement-payments-support-on-android
Add billingID to response of GetPaymentURL, as this value is the universal identifier of payment request, so it should be propagated by mobile clients
> GO-3023 Add billingID to response

- core/block/editor.go
- core/block/editor/basic/basic.go
- core/block/editor/basic/details.go
- core/block/editor/basic/details_test.go
- core/block/editor/participant.go
- core/block/editor_test.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
https://linear.app/anytype/issue/GO-3210/relationlinks-identity-and-globalname-are-not-added-to-participant
https://linear.app/anytype/issue/GO-3211/update-global-name-in-multispaces
1. Make globalName a derived relation, so it is included in Identity object on Init stage
2. Add relation links on details modification
> GO-3210 | GO-3211 Make globalName derived

- core/block/import/importer.go
- core/block/import/importer_test.go
https://linear.app/anytype/issue/GO-3173/send-to-client-number-of-objects-which-was-imported-within-one-import
Don't count root collection object in analytics, because we need to count only imported objects
> GO-3173: send to client number of objects which was imported within one import procedure

- cmd/usecasevalidator/main.go
- cmd/usecasevalidator/validators.go
https://linear.app/anytype/issue/GO-2673/implement-validator-on-usecase-addition-in-gallery
- exclude deleted object from archive
- exclude templates with no target type presented in the archive
- delete recommendedRelations of type objects in case these relations are not in the archive
> GO-2673 Exclude deleted objects

- pkg/lib/datastore/clientds/clientds.go
- pkg/lib/datastore/clientds/syncer.go
not waiting for syncer to finish and closing badger may result in nil deref
> GO-3311 syncer: wait on closer to avoid panics

- core/block/import/common/common.go
- core/block/import/common/common_test.go
If we have iconImage in text block, we
1. Check if it's file object and it exists in current import archive. If it exist, we update icon image value with new file object id
2. If file object is not exist in archive, we
* Check if it's a valid cid
* If it is a valid cid, we assume that file object is missing and mark it in icon image field in text block
* If it's not valid cid, we assume that it can be url from Notion and do nothing because we load it later in icon syncer
> GO-3150: fix importing of icons in callout block

- core/block/bookmark/bookmark_service.go
- core/block/editor/archive.go
- core/block/editor/converter/layout.go
- core/block/editor/dashboard.go
- core/block/export/export.go
- core/block/object/objectcreator/installer.go
- core/block/object/objectcreator/object_type.go
- core/block/object/objectcreator/systemobjectreviser.go
- core/block/service.go
- core/files/fileobject/fileindex.go
- core/files/fileobject/service.go
- core/indexer/reindex.go
- core/object.go
- pkg/lib/database/database.go
- pkg/lib/database/mock_ObjectStore.go
- pkg/lib/database/order.go
- pkg/lib/localstore/objectstore/mock_objectstore/mock_ObjectStore.go
- pkg/lib/localstore/objectstore/objects.go
- pkg/lib/localstore/objectstore/objects_test.go
- pkg/lib/localstore/objectstore/queries.go
- pkg/lib/localstore/objectstore/queries_test.go
- pkg/lib/localstore/objectstore/relations.go
- pkg/lib/localstore/objectstore/space.go
- util/testMock/objectstore_mock.go
https://linear.app/anytype/issue/GO-3410/remove-total-from-objectstorequery
Remove total return-value from Query method of ObjectStore, as it is not evaluated correctly
> GO-3410 Remove total from Query

- core/subscription/dep.go
- core/subscription/service_test.go
https://linear.app/anytype/issue/GO-2632/middleware-updates-details-of-system-objects-frequently#comment-21102ce0
The problem was in dependencies subscriptions of files. Files can be dependent objects of themselves, because they have icons with the same id as theirs. So I could try not to add to dependent objects the objects with the same id as original entry
> GO-2632: middleware updates details of system objects frequently

- util/builtinobjects/builtinobjects.go
https://linear.app/anytype/issue/GO-3476/change-default-use-case-get-started-to-a-new-one
Fix widget type of sets and recent in new Get Started usecase
> GO-3476 Set compact list instead of list

- core/block/editor/file/file.go
- core/block/editor/file/file_test.go
https://linear.app/anytype/issue/GO-3203/if-you-drag-and-drop-a-file-onto-a-set-or-collection-it-creates-a-link
Check Blocks restriction on Drag-n-Drop
> GO-3203 Check restrictions in DnD

- core/identity/ownidentity.go
- core/identity/ownidentity_test.go
https://linear.app/anytype/issue/GO-3541/avoid-sync-fetchglobalname-on-app-start
We should not do network operations on component start, so fetchGlobalName for ownIdentity should be done asyncrhonously
> GO-3541 Async fetchGlobalName

- core/block/export/export.go
- core/block/export/export_test.go
https://linear.app/anytype/issue/GO-3515/cannot-export-object-with-linked-objects
1. Skip export of recommended relation if it's not exist in object store
2. Add optimization - now we try to get derived objects only from object types or templates, because currently for relations it's useless as they have only system relations and type
> GO-3515: cannot export object with linked objects

- core/block/import/markdown/anymark/blocks_test.go
- core/block/import/markdown/anymark/renderer.go
https://linear.app/anytype/issue/GO-3537/missing-import-data-markdown-spaced-codeblock
* Then we get code block NodeKind during rendering markdown input, we forget to add text from code block to our buffer, which is used in anytype text block 
* So I write text from code block to buffer, so it will be added to text block in `CloseTextBlock` function
> GO-3537: Missing Import data - Markdown spaced codeblock

- core/syncstatus/spacesyncstatus/filestate.go
- core/syncstatus/spacesyncstatus/objectstate.go
- core/syncstatus/spacesyncstatus/spacestatus.go
- core/syncstatus/spacesyncstatus/spacestatus_test.go
https://linear.app/anytype/issue/GO-3640/dont-send-similar-sync-status-events
1. Fix possible race condition, which can possibly occur during cmd+r
2. Not send event if previous status of object and file sync is the same
3. Not send Syncing event, if syncing object number is not changed
> GO-3640: do not send similar events for space sync status

- core/block/template/service.go
- core/block/template/service_test.go
https://linear.app/anytype/issue/GO-3568/there-is-no-tag-in-details-though-it-is-featured
Add empty tag detail to all new objects
> GO-3568 Add tag to details of custom object

- core/block/template/service.go
- core/block/template/service_test.go
https://linear.app/anytype/issue/GO-3542/daily-journal-creation-date-is-wrong
We should not take AddedDate and CreationDate from template object
> GO-3542 Do not take Added and Creation dates from template

- core/block/editor/basic/extract_objects.go
- core/block/editor/basic/extract_objects_test.go
- docs/proto.md
- pb/protos/commands.proto
https://linear.app/anytype/issue/GO-3645/add-link-settings-to-blocklistconverttoobjects
Add block param in request `BlockListConvertToObjects` and use it to create link block in given object
> GO-3645: Add link settings to BlockListConvertToObjects

- core/domain/syncstatus.go
- core/syncstatus/detailsupdater/updater.go
- core/syncstatus/detailsupdater/updater_test.go
- core/syncstatus/spacesyncstatus/filestate.go
- core/syncstatus/spacesyncstatus/filestate_test.go
- core/syncstatus/spacesyncstatus/mock_spacesyncstatus/mock_SpaceIdGetter.go
- core/syncstatus/spacesyncstatus/objectstate.go
- core/syncstatus/spacesyncstatus/objectstate_test.go
- core/syncstatus/spacesyncstatus/spacestatus.go
- core/syncstatus/spacesyncstatus/spacestatus_test.go
- pkg/lib/core/smartblock/smartblock.go
1. Don't add sync relations to system objects
2. Send space sync event for all objects at start
3. Send sync status event if status is unknown
4. Not index notification object
> Fix sync bugs and notification object indexing

- util/anonymize/anonymize.go
- util/anonymize/anonymize_test.go
https://linear.app/anytype/issue/GO-3609/links-in-text-blocks-should-be-anonymized-in-debug-output
Make link marks of text blocks anonymized in a bunch of events on DebugTree
> GO-3609 Anonymize link marks in text blocks

- .github/workflows/test.yml
- disable race detector for tests when running inside the PR branch
- enable race detector for tests when merging into main
> GO-3746 ci: disable race for tests in pull requests

- core/subscription/collection.go
- core/subscription/group.go
- core/subscription/service.go
- core/subscription/simple.go
- core/subscription/sorted.go
https://linear.app/anytype/issue/GO-3561/the-checkbox-does-not-work-in-the-sets-in-some-relations
Changes coming to Subscription Service listener were not applying for entries of **/dep** subscriptions, because we were not iterating over them
> GO-3561 Apply changes for dep subs

- pkg/lib/localstore/objectstore/fixture.go
- pkg/lib/localstore/objectstore/indexer_store.go
- pkg/lib/localstore/objectstore/links.go
- pkg/lib/localstore/objectstore/objects.go
- pkg/lib/localstore/objectstore/queries.go
- add `isClosingCh` for the objectstore
- add waitgroup for store queries that are using iterator
- fail long queries fast when `isClosingCh` is closed. (not possible for all queries, requires refactoring)
- wait all queries to finish on objectStore close
> GO-3757 graceful shutdown for long objectstore queries

- core/block/editor/clipboard/clipboard.go
- core/block/editor/clipboard/clipboard_helpers_test.go
- core/block/editor/clipboard/clipboard_test.go
https://linear.app/anytype/issue/GO-3674/copy-file-blocks-between-spaces
On copying file blocks from one space to another we should create new file object with same hash and keys
> GO-3674 Create file object on copying block to other space

- metrics/events.go
- metrics/interceptors.go
- util/debug/debug.go
- util/debug/debug_test.go
- send most actual stacktrace when request is finished
- double check if it really contains the method goroutine
> GO-3747 stacktrace logger improvements

- core/subscription/dep.go
https://linear.app/anytype/issue/GO-3762/links-are-not-displayed-in-objects-of-set
We should add Links in a list of relations dependent subscription is built on, because links include not only objects mentioned in details, but also objects mentioned in blocks
> GO-3762 Add links as dependents

- core/block/editor/clipboard/clipboard_test.go
- core/block/editor/file/file_test.go
- core/block/editor/smartblock/links.go
- core/block/editor/smartblock/smartblock.go
- core/block/editor/smartblock/smartblock_test.go
- core/block/editor/smartblock/smarttest/smarttest.go
https://linear.app/anytype/issue/GO-3635/update-backlinks-reactively-in-the-objectstore
StateAppend did not update links of smartblock, as injectLinks was not called explicitly. Now injectLinks is called inside injectDerivedDetails, so changes are applied for objects on other devices even if they are not uploaded in cache.
Additionally some refactoring in smartblock pkg is made. Details are in the code comments
> GO-3635 Inject links along with derived relations + some smartblock refactoring

- core/block/editor/basic/extract_objects.go
- core/block/editor/basic/extract_objects_test.go
https://linear.app/anytype/issue/GO-3778/error-when-turning-into-object-in-the-bookmark-type
We should support turning blocks not only in links, but in other types of blocks that could handle some link on object (bookmark, file, dataview)
> GO-3778 Fix turning into bookmark

- pkg/lib/localstore/objectstore/queries.go
> GO-2973 Fix empty string

- .github/workflows/build.yml
- core/block/import/common/objectid/derivedobject.go
- core/syncstatus/spacesyncstatus/spacestatus.go
- core/syncstatus/spacesyncstatus/spacestatus_test.go
- core/syncstatus/syncsubscriptions/syncingobjects.go
- core/syncstatus/syncsubscriptions/syncsubscriptions.go
- core/syncstatus/syncsubscriptions/syncsubscriptions_test.go
> Merge release 6

- core/block/editor/basic/extract_objects.go
- core/block/editor/basic/extract_objects_test.go
- core/block/service.go
- core/block/template/service.go
- core/block/template/service_test.go
https://linear.app/anytype/issue/GO-3777/the-template-breaks-after-turn-into-object-in-the-template-editor
In case we are trying to convert blocks of template into objects and this template is chosen as basis for new blocks, app meets deadlock, because we are taking lock on template's smartblock twice.
I introduce new method of template service **CreateTemplateStateFromSmartBlock** that accepts smartblock directly as an argument and therefore does not need to take lock one more time
> GO-3777 Fix convert for templates

- core/block/editor/page.go
https://linear.app/anytype/issue/GO-3779/the-description-disappears-from-featured-relations-after-creating-an
CreationMigration wipes description from state. It seems we should remove this logic to allow descriptions in notes
> GO-3779 Allow description in notes

- core/block/editor/archive.go
- core/block/editor/archive_test.go
- core/block/object/objectcreator/installer.go
- pkg/lib/localstore/objectstore/objects.go
https://linear.app/anytype/issue/GO-3737/after-deleting-the-type-it-is-not-installed
Both archive object and bundle objects installer queried deleted/archived objects using objectstore.Query method.
However this method implicitely adds filters for deleted/archived objects, so query result wasn't always correct.
QueryRaw method should be used in cases like this
> GO-3737 Fix type reinstall

- core/block/editor/archive.go
- core/block/editor/archive_test.go
- core/block/object/objectcreator/installer.go
- core/block/object/objectcreator/installer_test.go
- pkg/lib/localstore/objectstore/objects.go
https://linear.app/anytype/issue/GO-3737/after-deleting-the-type-it-is-not-installed
Fix type reinstallation. The error was connected with implicit addition of isDeleted and isArchived filters to db query
> [release 6] GO-3737 - Fix type reinstall

- core/history/history.go
- core/history/history_test.go
https://linear.app/anytype/issue/GO-3870/historygetversions-ignore-limit-param
> GO-3870: HistoryGetVersions ignore limit param

- cmd/usecasevalidator/main.go
https://linear.app/anytype/issue/GO-3865/provide-name-of-use-case-from-gallery-for-imported-with-use-case
We do not check state and its blocks on nil, that's why usecase validator paniced sometimes
> GO-3865 Fix panic on analytics insert

- core/block/service.go
https://linear.app/anytype/issue/GO-3849/need-to-save-the-setcollection-if-you-have-not-entered-a-name
We need to unset DeleteIfEmpty flag in case source of set is set
> GO-3849 Do not GC set if source is set

- core/block/import/notion/api/files/file.go
We can't rename files in windows before we close it
> GO-3998 fix import of notion files foe windows 

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- space/internal/components/dependencies/spacewithctx.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser_test.go
https://linear.app/anytype/issue/GO-3814/add-origin-relation-to-all-files-as-recommended
SystemObjectReviser should be able to update list of recommendedRelations.
Origin was added for file object types (File, Image, Video, Audio) in #1436 , but object types' objects did not added it to their recommended relations in existing spaces. This PR fixes that
> GO-3814 Add recommendedRelations value revision for system types

- core/block/editor/state/state.go
- core/block/editor/state/state_test.go
Skip `coverId` in `FileRelationKeys` in case relation `coverType` is not marked as file
> fix coverId handling in FileRelationKeys

- util/persistentqueue/queue.go
in case notifyWaiters is called more than once (possible in case of Retry)
> GO-4118 fix possible panic in notifyWaiters

- core/indexer/fulltext.go
- pkg/lib/localstore/objectstore/indexer_store.go
- pkg/lib/localstore/objectstore/service.go
- pkg/lib/localstore/objectstore/spaceindex/fixture.go
- pkg/lib/localstore/objectstore/spaceindex/store.go
Add ids to the queue in one tx
> GO-4202 make the ft reindex logic atomic

- core/block/editor/state/state.go
- core/block/export/export.go
- pkg/lib/localstore/ftsearch/ftsearchbleve.go
- pkg/lib/localstore/ftsearch/ftsearchtantivy.go
- pkg/lib/localstore/ftsearch/ftsearchtantivy_test.go
- util/text/text.go
- util/text/text_test.go
> GO-4159 get rid of private info in errors from search

- core/block/editor/page.go
- core/block/editor/page_test.go
- core/indexer/reindex.go
- space/clientspace/space.go
- space/clientspace/space_test.go
- space/internal/components/builder/builder.go
https://linear.app/anytype/issue/GO-3967/implement-migration-from-tag-relation-options-to-tag-object-type
1. Add querying of relation option and tag relation to trigger migration during space init 
2. Add state migration for tag and relation options that removes unnecessary relations, update types and layouts
> GO-3967: implement migration from tag relation options to tag object

- core/kanban/group_tag.go
- core/object.go
- core/subscription/mock_subscription/mock_Service.go
- core/subscription/service.go
- core/subscription/service_test.go
- space/spacecore/mock_spacecore/mock_SpaceCoreService.go
https://linear.app/anytype/issue/GO-3977/deleted-tags-still-showing
On ObjectGroupSubscribe we used to call store.QueryRaw without isDeleted and isArchived filters, so deleted tags showed up as well
> GO-3977 Do not show deleted tags in kanban

- core/block/editor/basic/details.go
- pkg/lib/localstore/objectstore/spaceindex/relations.go
make `FetchRelationByKeys` works the same as `FetchRelationByKey` - to return bundled objects directly from map.
This was called via `ModifyParticipantAclState` and in case of empty objectstore (new account, reindex), failed to add the relationLinks.
RelationLinks will be removed next release, because we will store relation list in the type.
> GO-4282 reindex invalid participant permissions

- core/filestorage/rpcstore/clientmgr.go
- core/payments/payments.go
- util/contexthelper/context.go
- util/contexthelper/context_test.go
Mutex here was clearly used as a limiter mechanism so i replaced it with buffered chan. This way canceled GetSubscriptionStatus call will not hang on mutex.
> GO-4271 payments GetSubscriptionStatus: use limiter instead of mutex

- core/publish.go
- core/publish/service.go
implements initial support for publishing multiple files, implemented via ufs. For now, I'm just sending dummy assets (for testing purposes) and next step would be to send real web page assets, such as images. Same goes for renderer on gateway, -- it doesn't support any assets at the moment.
current structure of published ufs dir:
```
- keys.json <- encrypted with main key, has keys for all the other files
- index.json <- renderer input 
- asset1
- asset2....
```
Uploading implemented via same mechanism which we use for invites but for the future I'm thinking about how to implement it on top of  `UploadFile`. It will also allow us to get rid of custom encryption scheme (`keys.json`) and reuse standard anytype-heart encryption mechanics for file objects.  So we need a dedicated file type …
> Go 4256 read exported ipld tree with assets and render

- core/block/import/csv/converter.go
- core/block/import/csv/converter_test.go
- core/block/import/csv/testdata/transpose_not_matrix.csv
https://linear.app/anytype/issue/GO-4272/fix-an-objectimport-panics
The problem is that we create CSV reader with following option`csvReader.FieldsPerRecord = -1`. That means that we doesn't check number of column per row. And we allow to import files like this for example
```
name
price;1
```
I decided not to remove this check and allow to import such files, but I transform them into matrix, to avoid problems with transpose (because we assume that during transpose we have a matrix). So after normalization we will get csv table in slices with added empty strings - representation of missed columns 
before fix
```
[][]string{
[]string{"name"};
[]string{"price", "1"}
}
```
after fix
```
[][]string{
[]string{"name", ""};
[]string{"price", "1"}
}
```
> GO-4272: fix an ObjectImport panics

- core/file.go
> GO-1230 fix FileListOffload

- core/block/editor/state/state.go
- core/syncstatus/detailsupdater/updater.go
> GO-4373: Remove sync relations

- core/block/editor/participant.go
- core/block/editor/participant_test.go
We initialize title block before `SetDetails` call, so it is turned out to be empty after participant creation. 
So the fix is to call title block creation in `template.InitTemplate` after `SetDetails` call
> GO-4241: The name of the Space member is not displayed

- core/block/editor/basic/details.go
- core/block/editor/basic/details_test.go
- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
https://linear.app/anytype/issue/GO-4139/unhide-donetemplate-bugs
https://linear.app/anytype/issue/GO-4141/disable-the-ability-to-change-object-type-to-template
https://linear.app/anytype/issue/GO-4142/prohibit-creating-objects-with-type-template
Template type has become unhidden, so we should prohibit:
- creation of Template object without targetObjectType provided
- changing object's type to Template type
> GO-4139 | GO-4141 | GO-4142 - Restrict template creation

- core/block/restriction/object.go
- core/block/restriction/object_test.go
https://linear.app/anytype/issue/GO-4244/restricted-duplication-of-objects-in-the-menu
Duplication should be restricted for Chat object
> GO-4244 Restrict chat duplication

- core/block/backlinks/watcher.go
- core/block/backlinks/watcher_test.go
- core/block/collection/service.go
- core/block/collection/service_test.go
https://linear.app/anytype/issue/GO-4398/objects-title-disappears-when-added-via-collectionset
We can fix objects instant update on adding to collection, by updating backlinks relation directly in AddToCollection request
> GO-4398 Update backlinks on adding to collection

- core/block/source/date.go
- core/block/source/marshall_change_test.go
- core/block/source/mock_source/mock_Service.go
- core/block/source/service.go
- core/object.go
- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- pkg/lib/localstore/objectstore/fixture.go
- pkg/lib/localstore/objectstore/spaceindex/fixture.go
- pkg/lib/localstore/objectstore/spaceindex/objects.go
- pkg/lib/localstore/objectstore/spaceindex/queries.go
- pkg/lib/localstore/objectstore/spaceindex/queries_test.go
- pkg/lib/localstore/objectstore/spaceindex/store.go
https://linear.app/anytype/issue/GO-4219/support-the-date-format
https://linear.app/anytype/issue/GO-4339/if-i-add-a-date-as-an-object-the-details-for-this-object-do-not-have-a
- support unified date format "02 Sep 2024" while naming Date objects
- add spaceId to details of virtual Date objects
- add Date layout for Date type
> GO-4219 Support date format

- space/internal/components/migration/readonlyfixer/relationsfixer.go
- space/internal/components/migration/readonlyfixer/relationsfixer_test.go
- space/internal/components/migration/runner.go
- space/internal/components/migration/runner_test.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser_test.go
https://linear.app/anytype/issue/GO-4360/cannot-filter-by-action-done-in-0430
The problem were in system objects revision migrator. It didn't work for new `Done` relation revision, because it compares the same the same objects, because stores for space are the same. So I fixed it by adding store for Marketplace in function.
> GO-4360: Cannot filter by Action Done in 0.43.0

- core/block/detailservice/mock_detailservice/mock_Service.go
- core/block/detailservice/relations.go
- core/block/detailservice/relations_test.go
- core/block/detailservice/service.go
- core/block/object/objectcreator/mock_objectcreator/mock_Service.go
- core/relations.go
- docs/proto.md
- pb/protos/commands.proto
https://linear.app/anytype/issue/GO-3963/[epic]-release-8-or-date-as-an-object
Slightly change output of RelationListWithValue cmd. 
Instead of separate counters and relationKeys fields, unite them in list
> GO-3963 Change API for RelationListWithValue

- space/internal/components/migration/runner.go
- space/internal/components/migration/runner_test.go
Unit tests spent much time on initiating space indexes. If we init them before Mirgation runner start, migrations will be accomplished faster
> GO-4360 Fix migrator test again

- cmd/usecasevalidator/main.go
- cmd/usecasevalidator/validators.go
- core/block/export/export.go
- core/block/export/export_test.go
- FileObjects were not handled, because of dumb file name prefix check
- Remove relation options that are sticked to absent relations
- Delete mentions detail from objects, as it is derived
> Fix fileObjects handling in usecase validator

- core/block/detailservice/relations.go
- core/block/import/notion/api/block/text_test.go
- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
- core/block/service.go
- core/block/source/date.go
- core/block/source/service.go
- core/date/suggest.go
- pkg/lib/database/filter.go
- pkg/lib/database/filter_test.go
- space/mock_space/mock_Service.go
- space/service.go
- util/dateutil/util.go
- util/dateutil/util_test.go
https://linear.app/anytype/issue/GO-4530/revert-date-as-an-object-changes
We should return Dataview block and setOf relation to Date objects for backward compatibility with clients releasing 7.1
> GO-4530 Return dataview and setof to dates

- core/block/import/common/error.go
- core/block/import/common/error_test.go
https://linear.app/anytype/issue/GO-4475/incorrect-error-code-when-importing-unsuitable-files
Remove old check for errors, it was needed to support old protocol. Now protocol is supported, so it should be removed
> GO-4475: Incorrect error code when importing unsuitable files

- core/block/service.go
We should resolve spaceId for objects only if spaceId is missing from initial request
> Fix missing spaceId resolution

- core/block/detailservice/relations.go
- core/block/detailservice/relations_test.go
- core/block/editor/smartblock/smartblock.go
- core/block/import/notion/api/block/textobject.go
- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
- core/block/object/objectlink/dependent_objects.go
- core/block/service.go
- core/block/source/date.go
- core/date/date_test.go
- core/date/details.go
- core/date/suggest.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- pkg/lib/database/filter.go
- pkg/lib/database/filter_test.go
- util/dateutil/util.go
- util/dateutil/util_test.go
https://linear.app/anytype/issue/GO-4560/mentions-should-be-put-on-1st-place-in-relationlistwithvalue-output
- Mentions should appear as first relation in RelationListWithValue output (if presented)
- Rename Last Used date -> Last used date for consistency
- For dates with time included enrich date names with time hh:mm
> GO-4560 Mentions should be 1st in RelationsListWithValue response

- core/date/suggest.go
- go.mod
- util/dateutil/util.go
- util/dateutil/util_test.go
https://linear.app/anytype/issue/GO-4586/do-not-generate-long-ids
https://linear.app/anytype/issue/GO-4590/support-the-date-format-once-again
- We should not allow to generate second-precision date object ids for now, as old clients could not show these objects correctly
- Change date format to Mon, Dec 25, 2124 11:34 PM
> GO-4586 | GO-4590 - Do not generate long date ids + Change date format again

- core/date/suggest.go
- core/date/suggest_test.go
- core/object.go
https://linear.app/anytype/issue/GO-4587/objectsearch-by-ids-should-return-date-objects
If ObjectSearch request includes filters by id and values are date object ids, than response should be enriched with date objects' details
> GO-4587 ObjectSearch should return dates by ids

- core/block/editor/smartblock/links.go
- core/block/object/objectlink/dependent_objects.go
- core/block/object/objectlink/dependent_objects_test.go
https://linear.app/anytype/issue/GO-4586/do-not-generate-long-ids
Object could contain multiple limks/mentions of date objects pointing to the same day. 
However **links** relation should contain only single link to date object of the single day
> GO-4586 Unify date object ids in links

- core/block/editor/basic/details.go
- core/block/editor/converter/layout.go
- core/block/editor/converter/layout_test.go
- core/block/template/service.go
https://linear.app/anytype/issue/GO-4419/templates-for-setscollections
Layout converter asked space as a parameter in Convert just to get the id of Page object type to substitute is as default source in new set. It seems this logic is redundant, as all three clients render sets without source normally. Users are immediately headed to source choose on set object openning
> GO-4419 Fix panic on set template creation

- core/block/restriction/object.go
- core/block/source/date.go
- core/date/date_test.go
https://linear.app/anytype/issue/GO-4595/remove-menu-items-from-3-dots-in-the-object-widget
It is possible to do certain actions upon date object from 3 dots menu, because restrictions relation is not set to date source
> GO-4595 Add restrictions to date

- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/installer.go
- core/block/object/objectcreator/installer_test.go
https://linear.app/anytype/issue/GO-4490/the-type-is-not-deleted-a-second-time
On bundled type/relation reinstall we should unarchive it via Archive object
> GO-4490 Fix reinstall of archived objects

- core/block/detailservice/mock_detailservice/mock_Service.go
- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- pkg/lib/bundle/systemRelations.gen.go
- pkg/lib/bundle/systemRelations.json
https://linear.app/anytype/issue/GO-4608/layout-settings-on-the-object-type-level-or-desktop
LayoutWidth relation will be used by clients to set objects' width
> GO-4608 LayoutWidth relation for layout settings on desktop

- core/block/template/service.go
https://linear.app/anytype/issue/GO-4337/cannot-create-a-page
We should not allow creating objects from deleted or uninstalled templates
> GO-4337 Prohibit creating objects from deleted template

- core/date/suggest.go
- core/date/suggest_test.go
- core/object.go
- util/dateutil/util.go
- util/dateutil/util_test.go
https://linear.app/anytype/issue/GO-4647/add-date-to-global-search
https://linear.app/anytype/issue/GO-4635/improve-date-suggestion
- Add date objects to results of ObjectSearchWithMeta as well
- Suggest date objects on prefix
- Substitute Thu, 05 Dec, 2024 -> Thu, 5 Dec, 2024
> GO-4647 | GO-4635 - Improve dates suggestion in search

- core/anytype/account/service.go
- core/application/account_create_from_export.go
- core/block/editor/accountobject/accountobject.go
- core/block/editor/accountobject/accountobject_test.go
- core/block/editor/factory.go
- go.mod
- go.sum
- space/service.go
- space/service_test.go
- space/techspace/techspace.go
- space/waiter.go
- util/metricsid/metricsid.go
- util/metricsid/metricsid_test.go
> GO-4653: Simplify analytics id logic and add more verbose errors

- core/block/import/markdown/blockconverter.go
- core/block/import/markdown/import_test.go
- core/block/import/markdown/testdata/links.md
In case of wrong url in markdown link, I returned nil value. That makes block content nil, which is invalid state
> GO-4574 importing markdown file that contains broken link makes app crash

- core/subscription/service.go
Right now client can client multiple subscriptions with the same name in different spaces.
Then, when clients receive events they are ambiguous.
We should either add spaceId to all subscription events or scope the subscription to sessions as we discussed before.
This is a temp fix for the release
> GO-4598 call unsubscribe for all spaces to avoid dup subIds

- core/application/account_select.go
- core/application/account_select_test.go
In case of error during `AccountSelect`, I call `os.RemoveAll` for account directory, so it won't exist
> GO-4502 cleanup empty account folder on cold start

- core/block/export/export.go
- do not include types/relations in md export
- do not include home object(favorites) in anyblock export. Favorites are handled via isFavorite relation
> GO-4736 markdown exportimport creates a lot of page objects

- core/block/object/objectcreator/installer.go
- core/block/object/objectcreator/installer_test.go
- core/block/object/objectcreator/object_type.go
- core/block/object/objectcreator/object_type_test.go
- core/block/object/objectcreator/relation.go
https://linear.app/anytype/issue/GO-4232/add-every-system-relations-to-recommended-relations-to-make-a-list-in
On creation / installation of object types recommendedRelations and recommendedFeaturedRelations are being filled by system relations as well
> GO-4232 Add system relations to recommended

- pkg/lib/database/database.go
- pkg/lib/database/database_test.go
`ObjectSearch` no longer supported `NestedFilters` due to missing recursion in `FiltersFromProto` after details refactoring.
> GO-4144: Fix NestedFilters in FiltersFromProto

- core/block/export/export.go
- core/block/export/export_test.go
- core/block/import/common/common.go
- core/block/import/common/common_test.go
Add mapping of default object type id to the new one in import, so we get new id of default type in result collection object
> GO-4719: After import I can no longer add an object to a collection

- core/block/export/export.go
- core/block/export/export_test.go
- core/block/import/importer_test.go
- core/block/process/notificationprocess.go
- core/block/process/queue.go
- core/block/process/queue_test.go
- core/block/process/service.go
- docs/proto.md
- pb/protos/commands.proto
- util/builtinobjects/builtinobjects.go
1. Add new param in export request noProgress - to turn off progress and notification events.
2. Move logic of sending notifications from export service to queue service - I implemented existing interfaces `Notificationable` and `NotificationSender` (NotificationSender is used in processes service to send notifications)
3.  Remove queue.Stop() call as it doesn't do anything
> GO-4810: Make notifications optional in progress bar for export

- Makefile
- core/block/editor.go
- core/block/editor/basic/details.go
- core/block/editor/smartblock/smartblock.go
- core/block/editor/smartblock/smarttest/smarttest.go
- core/block/editor/state/event.go
- core/block/editor/state/state.go
- core/domain/details.go
- core/domain/details_test.go
- core/history/history_test.go
- core/object.go
- core/subscription/context.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
https://linear.app/anytype/issue/GO-4840/set-null-detail-on-objectrelationadd
- set null detail on ObjectRelationAdd to object if no detail for particular relation is set
- add absentRelations return value to StructDiff, so null values are recognized as valid
> GO-4840 Set null on ObjectRelationAdd

- core/block/editor/state/event.go
- core/block/editor/state/state.go
- core/history/history_test.go
- core/subscription/internalsub_test.go
https://linear.app/anytype/issue/GO-4840/set-null-detail-on-objectrelationadd
Check detail keys that are going to be removed. If struct diff is nil, while the list is not empty, we still need to generate event messages
> GO-4840 Check keys to unset from StructDiff

- core/block/editor/state/state.go
- core/block/editor/state/state_test.go
- core/details.go
Decided to rewrite this task as we are removing relation links. So I just set details as false for checkoboxes relations, if we add such relation to object
> GO-3189: set checkbox relation as false in ObjectRelationAdd command

- core/publish/service.go
- core/publish/service_test.go
- docs/proto.md
- pb/protos/commands.proto
1. Save `joinSpace` in `Version` field for server
2. Add new parameter in middleware pb model `PublishingState`
3. Retrieve `joinSpace` parameter from version and save it in pb model for client
> GO-4886: add joinSpace param in PublishState pb model

- core/block/restriction/object.go
https://linear.app/anytype/issue/GO-4881/remove-details-restriction-from-all-editable-types
As recommendedRelation lists are editable for the majority of types, we should remove Details restriction from page-, file- and set-like types
> GO-4881 Remove Details restriction from editable types

- core/block/collection/service.go
- core/block/editor/smartblock/detailsinject.go
https://linear.app/anytype/issue/GO-4762/template-picker-during-the-collection-creation-doesnt-work
- preserve internalFlags on collection subscription
- fix layout setting for Relation object type
> GO-4762 Fix template picker + Layout propagation

- core/block/source/source.go
- core/block/source/store.go
https://linear.app/anytype/issue/GO-4947/account-object-comes-with-chatderived-layout
Account object from tech space should have Profile layout, not ChatDerived
> GO-4947 Fix Account layout

- core/block/collection/service.go
https://linear.app/anytype/issue/GO-4762/template-picker-during-the-collection-creation-doesnt-work
When calling ObjectToCollection we should preserve **editorSelectTemplate** internal flag, so template picker remains
> GO-4762 Preserve template picker on ObjectToCollection

- core/block/export/export.go
- core/block/export/export_test.go
- core/block/object/objectlink/dependent_objects.go
- core/block/object/objectlink/dependent_objects_test.go
- core/publish/service.go
- docs/proto.md
- pb/protos/commands.proto
1. Add new parameter `includeBacklinks` in export
2. Add new parameter in `DependentObjectIds` function - NoBacklinks. If true, we will skip it
3. For regular export we ignore backlinks
> GO-4961: fix backlinks export

- core/publish/service.go
- core/publish/service_test.go
- docs/proto.md
- pb/protos/commands.proto
1. Add new parameter in `PublishState` model - details
2. Save details from objects store for each published objects in this field during `PublishingList` call. So clients can retrieve objects information from these details
https://linear.app/anytype/issue/GO-4945/bug-not-all-published-pages-are-shown-in-my-sites-settings
> GO-4945: Bug: not all published pages are shown in "My Sites" settings

- core/block/restriction/object.go
- core/files/file.go
https://linear.app/anytype/issue/GO-4985/cover-by-picture-in-gallery-view-of-sets-by-bookmarks-does-not-work
- fix layout of new images uploaded as bookmark picture
- remove Details restriction from Bookmark type
> GO-4985 Fix bookmark picture upload

- core/publish/service.go
Enables local dev publishing flow without publish sever via standalone cli renderer.
usage:
1. set the env var to e.g. renderer/test_snapshots/test-me 
`export ANYTYPE_LOCAL_PUBLISH_DIR=/home/zarkone/anytype/anytype-publish-renderer/test_snapshots/test-me`
Run the client with this env and publish a page. Make sure `test-me` was created with `index.json.gz` inside.
3. in renderer, adjust Makefile SNAPSHOT_PATH accordingly:
`SNAPSHOT_PATH:=./test_snapshots/test-me`
4. `make render` 
it will create `index.html` in renderer root
5. launch a static web server in renderer root:
```
cd /home/zarkone/anytype/anytype-publish-renderer/
python -m http.server 8011
```
6. Open http://localhost:8011 in browser
> GO-5000 add `ANYTYPE_LOCAL_PUBLISH_DIR` to override publish to server

- cmd/usecasevalidator/customusage.go
- cmd/usecasevalidator/validators.go
- core/block/export/export.go
- core/relationutils/recommended.go
- core/relationutils/recommended_test.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
https://linear.app/anytype/issue/GO-4823/provide-list-of-fields-to-support-toggle-inside-the-sidebar-and-file
1. Default list of hidden recommended relations for new types should include:
- Last modified date
- Last modified by
- Last opened date
- Added date
- Source
- Source object
- Import Type
- Origin 
2. Include all types of recommended relations to export and to system objects revisor check
> GO-4823 Fixes on hidden recommended relations

- core/block/editor/state/state.go
- core/block/editor/state/state_test.go
- pkg/lib/bundle/relation.gen.go
Handle unsplash `coverType` (5) in `FileRelationKeys()` function
> GO-5017: fix export of unsplash images

- core/block/export/export.go
- core/block/export/export_test.go
Use `CreatorModifierWorkspace` for dependent objects, so we can extract participants from according details
> GO-5047: Space Member is not displayed in Created by/last modified by

- core/history/history.go
- core/history/history_test.go
https://linear.app/anytype/issue/GO-5020/version-history-and-resolvedlayout
On HistoryShow we should inject `resolvedLayout` in details of smartblock's ObjectView along with `typeId` and `spaceId`, as all clients rely on `resolvedLayout` value when rendering object
> GO-5020 Inject resolvedLayout on HistoryShow

- core/block/detailservice/relations.go
- core/block/detailservice/relations_test.go
While evaluating conflicting relations we should take into account all 4 lists of recommended relations
> Include hidden and file relations when calculating conflicts

- core/block/editor/smartblock/dependencies_test.go
- core/block/editor/smartblock/smartblock.go
https://linear.app/anytype/issue/GO-5103/inject-layout-in-objectshow-and-indexation
We should inject layout to objects missing this detail, as we are going to get rid of layout in primitives and must support backward compatibility for objects
> GO-5103 Inject layout in smartblock

- core/converter/md/md.go
- Pdf layout was missing in condition checking if object is a file
> GO-5107: Fix wrong file extension and directory for pdf in markdown export

- core/publish/relationswhitelist.go
https://linear.app/anytype/issue/GO-5117/bookmarks-created-from-object-are-not-rendered
> GO-5117: bookmarks created from object are not rendered

- pkg/lib/bundle/relation.gen.go
- pkg/lib/bundle/relations.json
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser_test.go
https://linear.app/anytype/issue/GO-4320/the-relation-created-by-should-only-display-the-space-member-type
- refactor relationFormatObjectTypes detail check in SystemObjectReviser
- set Participant as relationFormatObjectType of CreatedBy relation
> GO-4320 Revise createdBy objectTypes

- core/block/bookmark/bookmark_service.go
- core/block/bookmark/bookmark_service_test.go
- core/block/delete.go
- core/block/editor/basic/extract_objects.go
- core/block/editor/basic/extract_objects_test.go
- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
- core/block/service.go
- core/block/template/service.go
- core/block/template/service_test.go
https://linear.app/anytype/issue/GO-5021/default-template-logic-change
Some changes on default template handling:
1. On new template creation we check defaultTemplateId field of target type. In case it is empty new template is set as default
2. On deletion of some template we check defaultTemplateId value of target type. If we are deleting default template, last edited template is chosen as default. If no templates left for particular type, empty template is set
3. On new object creation we check if requested templateId is valid or not. In case template is empty or could not be found, last edited template of terget type is taken as origin of new object
> GO-5021 Default template id logic change

- core/block/editor/spaceview.go
https://linear.app/anytype/issue/GO-5134/description-for-space-view-is-not-saved
Save description to spaceView details on Workspace object update
> GO-5134 Set description to space view

- pkg/lib/bundle/types.gen.go
- pkg/lib/bundle/types.json
- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
- space/internal/components/migration/systemobjectreviser/systemobjectreviser_test.go
https://linear.app/anytype/issue/GO-5184/migrate-icons-for-bundled-non-system-types
We should migrate icons for bundled non-system types as well
> GO-5184 Migrate icons for bundled non system types

- .github/scripts/is_runner_busy.sh
- .github/workflows/build.yml
- .github/workflows/nightly.yml
- .github/workflows/perftests-grafana.yml
- .github/workflows/perftests.yml
- .github/workflows/reusable_wait_for_perftest.yml
- .github/workflows/reusable_wait_for_self_hosted_mac_mini.yml
- .github/workflows/test.yml
> OPS-611 added concurrent execution logic for perftest and other tasks

- core/block/delete.go
- core/block/object/objectcreator/creator.go
- core/block/object/objectcreator/creator_test.go
- core/block/template/mock_template/mock_Service.go
- core/block/template/service.go
- core/block/template/templateimpl/impl.go
- core/block/template/templateimpl/impl_test.go
https://linear.app/anytype/issue/GO-5021/default-template-logic-change
We should fallback to empty template:
- if empty templateId is provided
- if template could not be found
- if template marked as default is deleted
> GO-5021 Fallback to empty template

- core/block/editor/converter/layout.go
With primitives layoutAlign goes from type, so we need to exclude implicit setting of this detail on layout conversion
> Fix - Do not set align for tasks

- core/block/editor/converter/layout.go
https://linear.app/anytype/issue/GO-5414/the-headerfeatured-relations-is-not-displayed-in-the-set
We should not include setOf relation to featured for new sets, as now this parameter is defined in recommendedFeaturedRelations of Set type
> GO-5414 Fix featured relations for sets

- core/block/restriction/object.go
https://linear.app/anytype/issue/GO-5408/blocks-from-the-editor-are-moved-to-the-type-in-the-widget
Add Blocks restriction to types, so DnD to type widget will be prohibited
> GO-5408 Add Blocks restriction to types

- core/block/editor/template/template.go
- core/block/editor/workspaces.go
https://linear.app/anytype/issue/GO-5423/a-new-bookmark-is-created-without-a-property-from-the-type
We should not modify featuredRelations on template apply
> GO-5423 Remove featuredRelations from Bookmark

- core/block/editor/objecttype.go
https://linear.app/anytype/issue/GO-5338/delete-all-system-descriptions-for-types-and-relations-for-users
We should remove Description detail for all bundled type objects
> GO-5338 Delete description migration for object types

- core/block/editor/smartblock/detailsinject.go
- core/domain/genericmap.go
https://linear.app/anytype/issue/GO-5346/make-possible-to-change-the-note-layout-into-basic-etc
ResolvedLayout used to be inserted to state via UpdatePendingLocalDetails mechanism on smartblock Init, that's why conversion from Note did not work for objects that were not in cache
> GO-5346 Fix convert from Note

- core/block/restriction/object.go
- core/indexer/reindex.go
- pkg/lib/bundle/systemTypes.gen.go
- pkg/lib/bundle/systemTypes.json
https://linear.app/anytype/issue/GO-5261/[next]-make-type-certain-deletable
https://linear.app/anytype/issue/GO-5338/delete-all-system-descriptions-for-types-and-relations-for-users
- We should exclude Note and Task from system types, so they will not be reinstalled on space start
- Increase reindex counter, so description migration will be run for all bundled types
> GO-5261 | GO-5338 - Exclude Note & Task from system

- core/block/editor/lastused/lastused.go
- core/block/editor/lastused/lastused_test.go
https://linear.app/anytype/issue/GO-5404/make-the-correct-order-in-the-type-library
On space creation we set different values of lastUsedDate to bundled types, so they will be similarly sorted in all new spaces.
New order of types arrives
> GO-5404 Update initial order by lastUsedDate

- pkg/lib/localstore/objectstore/spaceindex/relations.go
https://linear.app/anytype/issue/GO-5461/after-migration-the-graph-displays-the-old-icons-there-is-no-iconname
Graph used to show old icons for types that migrated from older versions.
The problem was in the absence of **globalName** and **iconName** relations in object store, these relations just were not added to space as objects.
The fix adds missing system relations to response of ListAllRelations method
> GO-5461 Include all system relations on store.ListAllRelations

- core/block/editor/converter/layout.go
https://linear.app/anytype/issue/GO-5455/default-object-type-does-not-change-in-the-type-settings
Clients used to set defaultTypeId value as list of strings, so the value was not fetched correctly from anystore
> GO-5455 Fix defaultTypeId setting for new lists

- core/block/editor/smartblock/smartblock.go
https://linear.app/anytype/issue/GO-5451/after-migration-not-all-types-are-displayed-in-the-existing-object-in
We should unset isReadonly relation in case Delete or Blocks restriction was removed from object
> GO-5451 Unset isReadonly on restrictions change

- core/block/dataviewservice/service.go
- core/block/dataviewservice/service_test.go
https://linear.app/anytype/issue/GO-5402/after-remove-from-type-and-adding-a-new-property-all-properties-are
We should not update RelationLinks of dataview block on view relations update.
Fisrt list contains relations common for all views of dataview, while second contains layout settings for particular views (visibility, width, etc.)
> GO-5402 Fix view relations update

- core/relationutils/recommended.go
- core/relationutils/recommended_test.go
Fix default order for featured relations, so most types after migration won't face conflicting layout
> Fix default featured relations order

- core/block/editor.go
- core/block/import/common/objectcreator/objectcreator.go
- core/block/import/importer.go
- core/widget.go
https://linear.app/anytype/issue/GO-5475/2-identical-widgets-are-created-after-installing-an-experience-from
In case of import from gallery we have already added link to collection to widgets, so after import we need to check if such link block already exists in widget object
> GO-5475 Fix duplicated collection widget block on import from gallery

- core/block/collection/service.go
https://linear.app/anytype/issue/GO-5352/the-added-objects-are-not-displayed-in-the-inline-collection
We should add 'collection' hook on every collection update, because it could be out of cache
> GO-5352 Add collection hook on every update

- core/block/detailservice/service.go
https://linear.app/anytype/issue/GO-5531/date-relations-cant-be-cleared-when-doing-a-bulk-edit-of-the-relation
Support batch unset of details
> GO-5531 Support batch details unset

- space/internal/components/migration/systemobjectreviser/systemobjectreviser.go
https://linear.app/anytype/issue/GO-5487/property-changes-in-object-types-are-not-persistent-changes-are-gone
https://linear.app/anytype/issue/GO-5623/default-task-properties-reset-after-editing-and-restarting-anytype
https://linear.app/anytype/issue/GO-5506/i-cant-customize-the-properties-header-is-this-a-bug
https://linear.app/anytype/issue/GO-5512/type-icon-reverts-to-default
https://linear.app/anytype/issue/GO-5564/hiding-property-does-not-work-on-restart-of-the-anytype-desktop
Revision detail did not use to be updated for non-system bundled types, that's why lists of recommended relations and icon were updated every time on restart
> GO-5487 Fix revision of non system types

- core/block/editor/objecttype.go
- core/block/import/common/objectcreator/objectcreator.go
https://linear.app/anytype/issue/GO-5424/do-a-migration-when-types-recommended-layout-is-missing
We should set default value **basic** for recommendedLayout detail on types import both for new and already installed types
> GO-5424 Do migration for empty rec layout on import

- core/pushnotification/keys.go
- space/internal/components/aclobjectmanager/aclobjectmanager.go
https://linear.app/anytype/issue/GO-5638/the-app-crashes-after-remove-member
Symmetric key of ACL current state could be nil
> GO-5638 Fix panic on symm key derivation

- space/internal/components/spaceloader/loadingspace.go
> GO-5612: Refactor loading, make sure that setLoadErr is set when not

- core/block/chats/chatsubscription/service.go
- util/futures/future.go
- util/futures/future_test.go
We didn't have any mechanism to deal with the situation when manager initializes with error. To fix it, I introduced futures, the values that could be asynchronously resolved either to value or to error
> GO-5673: Chats: fix init for subscription manager when error occurs

- core/block/backlinks/watcher.go
- core/block/backlinks/watcher_test.go
- core/domain/id.go
- pkg/lib/localstore/objectstore/spaceindex/store.go
- pkg/lib/localstore/objectstore/spaceindex/submanager.go
- pkg/lib/localstore/objectstore/spaceindex/update.go
https://linear.app/anytype/issue/GO-4678/backlinks-watcher-is-failing-to-resolve-space-id
- Propagate spaceId directly from store
- In case object has link on object from other space, we should parse spaceId from id
> GO-4678 Propagate spaceId to backlinks watcher

- core/gallery/gallery.go
https://linear.app/anytype/issue/GO-5716/dont-pass-url-to-error
We should not pass url on error on DownloadManifest request
> GO-5716 Do not pass url on DownloadManifest error

- core/block/editor/stext/text.go
- core/block/editor/stext/text_test.go
https://linear.app/anytype/issue/GO-5624/changing-bullets-to-checkboxes-in-bulk-doesnt-change-whole-selection
We should apply style to all blocks
> GO-5624 Apply style to children blocks

- core/block/import/common/objectid/deriveobject_test.go
- core/block/import/common/objectid/existingobject.go
https://linear.app/anytype/issue/GO-4295/multi-select-relation-not-displaying-values-that-are-already-entered
We used to check if imported relation already existed in target space by format+name+layout. However, relationKey detail should be used instead of name, as it could not be modified by user
> GO-4295 Ignore relations with existing key

- core/device/service.go
- core/device/service_test.go
https://linear.app/anytype/issue/GO-4621/loaddevices-panic-synthetic
On loadDevices we used to first fetch device object from space by GetObject and on failure DeriveObject.
Sometimes peers to fetch device object became available between these calls, so that leaded to ErrTreeExists error, that was not catched properly.
GetObject and DeriveObject must be switched. Ctx is provided with PeerFindDeadline=30 secs and ResponsiblePeers key
> GO-4621 Fix panic on load devices

- core/block/import/common/common.go
https://linear.app/anytype/issue/GO-5798/remove-random-icons-from-imported-objects-in-markdown
Let's remove random icons insertion on MD import. Users are complaining they need to remove emojis manually afterwards
> GO-5798 Remove rendom icons on import

- core/block/editor/table/editor.go
- core/block/editor/table/editor_test.go
- core/block/editor/table/table.go
https://linear.app/anytype/issue/GO-1173/sort-table-alphabetically-accents-show-up-after-z
Introduce strings sort with collator that helps to order words with special characters like João
> GO-1173 Fix alpha sort in tables

- core/block/export/export.go
- core/export.go
- docs/proto.md
- pb/protos/commands.proto
- Replace `includeJsonSchema` flag with a more descriptive `mdIncludePropertiesAndSchema` flag
- Set `mdIncludePropertiesAndSchema` to false for `ExportSingleInMemory`
- Don't throw error for empty result data in `ExportSingleInMemory`, which occurs during participant export
> GO-5923: Fix markdown export after property export changes

- core/block/editor/dataview/dataview.go
- pkg/lib/localstore/objectstore/spaceindex/relations.go
https://linear.app/anytype/issue/GO-6044/blockdataviewrelationset-code-object-not-found-in-space-index
We should return Relation data from store even if relation object is archived or deleted
> GO-6044 Fix relation fetch on dataview operations

- core/block/import/markdown/anymark/renderer.go
https://linear.app/anytype/issue/GO-6031/i-cannot-open-certain-objects-anymore-since-04740-beta
We had a bug on Markdown import that leaded to creation of links with the content of the very md file. Client gets stuck trying to open resulting page
> GO-6031 Fix auto links creation on md import

- core/block.go
- core/block/cache/cache.go
- core/block/editor.go
https://linear.app/anytype/issue/GO-5848/make-events-in-blocklistmovetoexistingobjects-sync-in-response
Make events sync for BlockListMoveToExistingObject
> GO-5848 Add sync events to BlockMoveToExistingObject

- metrics/metrics.go
https://linear.app/anytype/issue/GO-2214/bookmarks-add-metrics-for-blocked-requests
We need to set mw as subsystem for linkpreviewstatus counter
> GO-2214 Fix linkpreview counter opts

- util/linkpreview/linkpreview.go
- util/linkpreview/linkpreview_test.go
https://linear.app/anytype/issue/GO-4784/do-not-do-previewsbookmarks-for-private-links
Let's exclude X-Frame-Options response tag check, as it blocks preview for such sites as vk.com and anytype.io
> GO-4784 Exclude x-frame-opts tag check

- core/block/editor/basic/details.go
- core/block/editor/basic/details_test.go
Add logging on internal details deletion.
We can remove it, when we are sure clients got rid of internal relations removing logic
> Add logging on internal details removal

- core/block/editor/order/order.go
- core/block/object/objectcreator/object_type.go
- pkg/lib/database/database.go
https://linear.app/anytype/issue/GO-6278/ensure-that-widget-for-the-newly-created-type-is-positioned-at-top-of
We should set current time to lastUsedDate to sort new type as first, if no custom order is set
> GO-6278 Make new types first

- core/converter/md/md.go
- core/converter/md/md_test.go
https://linear.app/anytype/issue/GO-3743/incorrect-indentation-of-nested-code-blocks-in-exported-markdown-files
We must save indents for code blocks on markdown import
> GO-3743 Fix md import of code blocks with indentation

- core/block/editor/order/order.go
- core/block/object/objectcreator/object_type.go
https://linear.app/anytype/issue/GO-6278/ensure-that-widget-for-the-newly-created-type-is-positioned-at-top-of
Ser orderId to all new custom types to set new types at list top
> GO-6278 Set OrderId to new types - HOTFIX
